In [ ]:
!git clone https://github.com/gelab-uiuc/CS598-GBL.git

Cloning into 'CS598-GBL'...
remote: Enumerating objects: 345, done.
remote: Counting objects: 100% (125/125), done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 345 (delta 88), reused 20 (delta 20), pack-reused 220 (from 1)
Receiving objects: 100% (345/345), 11.88 MiB | 34.35 MiB/s, done.
Resolving deltas: 100% (142/142), done.

In [ ]:
%cd CS598-GBL/protein

/content/CS598-GBL/protein

In [ ]:
import torch
print(torch.__version__)
print(torch.version.cuda)

2.10.0+cpu
None

In [ ]:
!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-2.10.0+cu128.html

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 126.1 MB/s eta 0:00:00

In [ ]:
pip install fair-esm

Collecting fair-esm
  Downloading fair_esm-2.0.0-py3-none-any.whl.metadata (37 kB)
Downloading fair_esm-2.0.0-py3-none-any.whl (93 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.1/93.1 kB 8.2 MB/s eta 0:00:00
Installing collected packages: fair-esm
Successfully installed fair-esm-2.0.0

In [ ]:
!pip install biopython mdtraj hydra-core omegaconf ml_collections einops py3Dmol modelcif GPUtil tmtools pyyaml

Collecting biopython
  Downloading biopython-1.87-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting mdtraj
  Downloading mdtraj-1.11.1.post1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.6 kB)
Collecting hydra-core
  Downloading hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: omegaconf in /usr/local/lib/python3.12/dist-packages (2.3.0)
Collecting ml_collections
  Downloading ml_collections-1.1.0-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (0.8.2)
Collecting py3Dmol
  Downloading py3dmol-2.5.4-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting modelcif
  Downloading modelcif-1.7-py3-none-any.whl.metadata (3.4 kB)
Collecting GPUtil
  Downloading GPUtil-1.4.0.tar.gz (5.5 kB)
  Preparing metadata (setup.py) ... done
Collecting tmtools
  Downloading tmtools-0.3.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (6.0.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from biopython) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from mdtraj) (1.16.3)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from mdtraj) (3.3.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from mdtraj) (26.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from hydra-core) (4.9.3)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from ml_collections) (1.4.0)
Collecting ihm>=2.10 (from modelcif)
  Downloading ihm-2.10.tar.gz (401 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 401.2/401.2 kB 8.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: msgpack in /usr/local/lib/python3.12/dist-packages (from ihm>=2.10->modelcif) (1.1.2)
Downloading biopython-1.87-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 60.7 MB/s eta 0:00:00
Downloading mdtraj-1.11.1.post1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 146.1 MB/s eta 0:00:00
Downloading hydra_core-1.3.2-py3-none-any.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.5/154.5 kB 13.2 MB/s eta 0:00:00
Downloading ml_collections-1.1.0-py3-none-any.whl (76 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.7/76.7 kB 6.6 MB/s eta 0:00:00
Downloading py3dmol-2.5.4-py2.py3-none-any.whl (7.2 kB)
Downloading modelcif-1.7-py3-none-any.whl (47 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 kB 4.2 MB/s eta 0:00:00
Downloading tmtools-0.3.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 70.7 MB/s eta 0:00:00
Building wheels for collected packages: GPUtil, ihm
  Building wheel for GPUtil (setup.py) ... done
  Created wheel for GPUtil: filename=GPUtil-1.4.0-py3-none-any.whl size=7392 sha256=e03cf0f38dbbf19dbc0ced46523b477acf86f9f7d4d34a10deb9d2f18f54a10b
  Stored in directory: /root/.cache/pip/wheels/92/a8/b7/d8a067c31a74de9ca252bbe53dea5f896faabd25d55f541037
  Building wheel for ihm (pyproject.toml) ... done
  Created wheel for ihm: filename=ihm-2.10-cp312-cp312-linux_x86_64.whl size=394720 sha256=d42d2162c67a9dd5390ed6a01bd5b9b6bbd992d577c0a0434ed07e027e3b8e23
  Stored in directory: /root/.cache/pip/wheels/0f/1a/5e/72c91766baf4ae6b7e3275e4b005de5a5fecfbf4d6f5979c39
Successfully built GPUtil ihm
Installing collected packages: py3Dmol, GPUtil, tmtools, ml_collections, ihm, biopython, modelcif, mdtraj, hydra-core
Successfully installed GPUtil-1.4.0 biopython-1.87 hydra-core-1.3.2 ihm-2.10 mdtraj-1.11.1.post1 ml_collections-1.1.0 modelcif-1.7 py3Dmol-2.5.4 tmtools-0.3.0

In [ ]:
!pip install -U jax

Requirement already satisfied: jax in /usr/local/lib/python3.12/dist-packages (0.7.2)
Collecting jax
  Downloading jax-0.10.0-py3-none-any.whl.metadata (13 kB)
Collecting jaxlib<=0.10.0,>=0.10.0 (from jax)
  Downloading jaxlib-0.10.0-cp312-cp312-manylinux_2_27_x86_64.whl.metadata (1.3 kB)
Requirement already satisfied: ml_dtypes>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from jax) (0.5.4)
Requirement already satisfied: numpy>=2.0 in /usr/local/lib/python3.12/dist-packages (from jax) (2.0.2)
Requirement already satisfied: opt_einsum in /usr/local/lib/python3.12/dist-packages (from jax) (3.4.0)
Requirement already satisfied: scipy>=1.14 in /usr/local/lib/python3.12/dist-packages (from jax) (1.16.3)
Downloading jax-0.10.0-py3-none-any.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 72.9 MB/s eta 0:00:00
Downloading jaxlib-0.10.0-cp312-cp312-manylinux_2_27_x86_64.whl (85.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.0/85.0 MB 31.9 MB/s eta 0:00:00
Installing collected packages: jaxlib, jax
  Attempting uninstall: jaxlib
    Found existing installation: jaxlib 0.7.2
    Uninstalling jaxlib-0.7.2:
      Successfully uninstalled jaxlib-0.7.2
  Attempting uninstall: jax
    Found existing installation: jax 0.7.2
    Uninstalling jax-0.7.2:
      Successfully uninstalled jax-0.7.2
Successfully installed jax-0.10.0 jaxlib-0.10.0

In [ ]:
!git clone https://github.com/dauparas/ProteinMPNN.git

Cloning into 'ProteinMPNN'...
remote: Enumerating objects: 634, done.
remote: Counting objects: 100% (256/256), done.
remote: Compressing objects: 100% (124/124), done.
remote: Total 634 (delta 137), reused 132 (delta 132), pack-reused 378 (from 1)
Receiving objects: 100% (634/634), 119.90 MiB | 39.98 MiB/s, done.
Resolving deltas: 100% (290/290), done.

In [ ]:
!pip install -q biotite

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.2/57.2 MB 43.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 84.9 MB/s eta 0:00:00

In [ ]:
#This code is to deal with version inconsistency
#Otherwise raises
#ValueError: mutable default <class 'esm.esmfold.v1.trunk.StructureModuleConfig'> for field structure_module is not allowed: use default_factory
#https://github.com/facebookresearch/esm/issues/696
#https://github.com/asarigun/esm/tree/main/esm/esmfold/v1
#Based on the comit messages, there should be debugging in esmfold.py&trunk.py
from pathlib import Path
import esm

esm_dir = Path(esm.__file__).resolve().parent
print("ESM package dir:", esm_dir)

esmfold_py = esm_dir / "esmfold" / "v1" / "esmfold.py"
txt = esmfold_py.read_text()
if "from dataclasses import dataclass, field" not in txt:
    txt = txt.replace(
        "from dataclasses import dataclass",
        "from dataclasses import dataclass, field")
txt = txt.replace(
    "trunk: T.Any = FoldingTrunkConfig()",
    "trunk: T.Any = field(default_factory=FoldingTrunkConfig)")
esmfold_py.write_text(txt)

trunk_py = esm_dir / "esmfold" / "v1" / "trunk.py"
txt = trunk_py.read_text()
if "from dataclasses import dataclass, field" not in txt:
    txt = txt.replace(
        "from dataclasses import dataclass",
        "from dataclasses import dataclass, field")
txt = txt.replace(
    "structure_module: StructureModuleConfig = StructureModuleConfig()",
    "structure_module: StructureModuleConfig = field(default_factory=StructureModuleConfig)")
trunk_py.write_text(txt)
print("Patched:", esmfold_py)
print("Patched:", trunk_py)

ESM package dir: /usr/local/lib/python3.12/dist-packages/esm
Patched: /usr/local/lib/python3.12/dist-packages/esm/esmfold/v1/esmfold.py
Patched: /usr/local/lib/python3.12/dist-packages/esm/esmfold/v1/trunk.py

In [ ]:
import os
import time
import numpy as np
import hydra
import torch
import subprocess
import logging
import pandas as pd
import shutil
from datetime import datetime
from biotite.sequence.io import fasta
import GPUtil
from typing import Optional, Union, List
from analysis import utils as au
from analysis import metrics
from data import utils as du
from omegaconf import DictConfig, OmegaConf
from openfold.data import data_transforms
import esm
from pathlib import Path
import mdtraj as md
from openfold.np import residue_constants
from tmtools import tm_align
from openfold.utils.superimposition import superimpose
from tqdm import tqdm
import re

ModuleNotFoundError: No module named 'analysis'

In [ ]:
class DictToObject:
    def __init__(self, dictionary):
        for key, value in dictionary.items():
            if isinstance(value, dict):
                setattr(self, key, DictToObject(value))
            else:
                setattr(self, key, value)

"/content/torch_hub"
"/content/CS598-GBL/protein/ProteinMPNN"

In [ ]:
#pt_hub_dir: /content/torch_hub
#pmpnn_dir: /content/CS598-GBL/protein/ProteinMPNN
#seed: 42
#foldseek_database: /home/shuaikes/server2/shuaikes/projects/protein-evaluation-notebook/foldseek_database/pdb

In [ ]:
import yaml

In [ ]:
def load_config(file_path):
    with open(file_path, "r") as f:
        config = yaml.safe_load(f)
    return config

In [ ]:
config_dict = load_config("./configs/evaluation.yaml")
config_dict["pt_hub_dir"] = "/content/torch_hub"
config_dict["pmpnn_dir"] =  "/content/CS598-GBL/protein/ProteinMPNN"
config_dict["seed"] = 42
config_dict

{'pt_hub_dir': '/content/torch_hub',
 'pmpnn_dir': '/content/CS598-GBL/protein/ProteinMPNN',
 'seed': 42,
 'foldseek_database': '/home/shuaikes/server2/shuaikes/projects/protein-evaluation-notebook/foldseek_database/pdb'}

In [ ]:
!apt-get install -y aria2

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libaria2-0 libc-ares2
The following NEW packages will be installed:
  aria2 libaria2-0 libc-ares2
0 upgraded, 3 newly installed, 0 to remove and 42 not upgraded.
Need to get 1,513 kB of archives.
After this operation, 5,441 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libc-ares2 amd64 1.18.1-1ubuntu0.22.04.3 [45.1 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libaria2-0 amd64 1.36.0-1 [1,086 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 aria2 amd64 1.36.0-1 [381 kB]
Fetched 1,513 kB in 0s (12.4 MB/s)
Selecting previously unselected package libc-ares2:amd64.
(Reading database ... 122354 files and directories currently installed.)
Preparing to unpack .../libc-ares2_1.18.1-1ubuntu0.22.04.3_amd64.deb ...
Unpacking libc-ares2:amd64 (1.18.1-1ubuntu0.22.04.3) ...
Selecting previously unselected package libaria2-0:amd64.
Preparing to unpack .../libaria2-0_1.36.0-1_amd64.deb ...
Unpacking libaria2-0:amd64 (1.36.0-1) ...
Selecting previously unselected package aria2.
Preparing to unpack .../aria2_1.36.0-1_amd64.deb ...
Unpacking aria2 (1.36.0-1) ...
Setting up libc-ares2:amd64 (1.18.1-1ubuntu0.22.04.3) ...
Setting up libaria2-0:amd64 (1.36.0-1) ...
Setting up aria2 (1.36.0-1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

In [ ]:
!aria2c --version

aria2 version 1.36.0
Copyright (C) 2006, 2019 Tatsuhiro Tsujikawa

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.11 libxml2/2.9.12 sqlite3/3.36.0 GnuTLS/3.7.1 nettle GMP/6.2.1 c-ares/1.17.1 libssh2/1.10.0
Compiler: gcc 11.2.0
  built by  x86_64-pc-linux-gnu
  on        Aug 21 2021 15:26:28
System: Linux 6.6.113+ #1 SMP Mon Feb  2 12:27:57 UTC 2026 x86_64

Report bugs to https://github.com/aria2/aria2/issues
Visit https://aria2.github.io/

In [ ]:
from EvalRunner_jupyter import EvalRunner

In [ ]:
config_dict = load_config("./configs/evaluation.yaml")
conf = DictToObject(config_dict)
EvalModel = EvalRunner(conf)

installing libs...
installing openfold...
installing esmfold...

In [ ]:
!pip install deepspeed

Collecting deepspeed
  Downloading deepspeed-0.18.9.tar.gz (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 36.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from deepspeed) (0.8.2)
Collecting hjson (from deepspeed)
  Downloading hjson-3.1.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: msgpack in /usr/local/lib/python3.12/dist-packages (from deepspeed) (1.1.2)
Collecting ninja (from deepspeed)
  Downloading ninja-1.13.0-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from deepspeed) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from deepspeed) (26.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from deepspeed) (5.9.5)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from deepspeed) (9.0.0)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from deepspeed) (2.12.3)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from deepspeed) (2.10.0+cu128)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from deepspeed) (4.67.3)
Requirement already satisfied: nvidia-ml-py in /usr/local/lib/python3.12/dist-packages (from deepspeed) (13.595.45)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->deepspeed) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->deepspeed) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->deepspeed) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->deepspeed) (0.4.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (3.25.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->deepspeed) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch->deepspeed) (1.5.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->deepspeed) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->deepspeed) (3.0.3)
Downloading hjson-3.1.0-py3-none-any.whl (54 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.0/54.0 kB 7.9 MB/s eta 0:00:00
Downloading ninja-1.13.0-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (180 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.7/180.7 kB 8.5 MB/s eta 0:00:00
Building wheels for collected packages: deepspeed
  Building wheel for deepspeed (setup.py) ... done
  Created wheel for deepspeed: filename=deepspeed-0.18.9-py3-none-any.whl size=1820408 sha256=61842732f3a2616a543cf8934452ed88681257dff15c3390df13838494ba0d8a
  Stored in directory: /root/.cache/pip/wheels/14/ff/77/6df576c7f26969435706ee20282924bef2c06ec6763192d0ab
Successfully built deepspeed
Installing collected packages: hjson, ninja, deepspeed
Successfully installed deepspeed-0.18.9 hjson-3.1.0 ninja-1.13.0

# RMSD

In [ ]:
pdb_path = "/content/CS598-GBL/protein/example_data/length_70/sample_0"
sc_output_dir = os.path.join(pdb_path, "self_consistency")
os.makedirs(sc_output_dir, exist_ok=True)
sc_results = EvalModel.calc_designability(sc_output_dir, pdb_path)
sc_results

/usr/local/lib/python3.12/dist-packages/jaxlib/plugin_support.py:91: RuntimeWarning: JAX plugin jax_cuda12_plugin version 0.7.2 is installed, but it is not compatible with the installed jaxlib version 0.10.0, so it will not be used.
  warnings.warn(
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

,tm_score,bb_rmsd,sample_path,header,sequence,ptm,plddt,pae
0,0.810827,2.176162,/content/CS598-GBL/protein/example_data/length...,"T=0.1, sample=1, score=0.9713, global_score=0....",KTLTKMKVKVEDKNINLEDIKKIVKEVGVNVEIEIDEKNNEVIITA...,0.773397,86.431992,3.044483
1,0.899643,1.780979,/content/CS598-GBL/protein/example_data/length...,"T=0.1, sample=2, score=1.0213, global_score=1....",SEKTKLLVKISDKSIDKEDIEKIVKEEGLDVEIEIDKETNTVTITA...,0.813963,89.776306,2.412084
2,0.805529,1.944001,/content/CS598-GBL/protein/example_data/length...,"T=0.1, sample=3, score=1.0766, global_score=1....",MELTKMLVKVKNPEINLEDIRKIVEEEGLDVEIEIDEETNTVTVTA...,0.585066,71.085335,7.499335

In [ ]:
pdb_path = "/content/sample01"
sc_output_dir = os.path.join(pdb_path, "self_consistency")
os.makedirs(sc_output_dir, exist_ok=True)
sc_results = EvalModel.calc_designability(sc_output_dir, pdb_path)
sc_results

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

,tm_score,bb_rmsd,sample_path,header,sequence,ptm,plddt,pae
0,0.672062,6.006414,/content/sample01/self_consistency/esmf/sample...,"T=0.1, sample=1, score=1.0735, global_score=1....",ERVEEEYRVVYDDDPATARAKAVADAAATLERLWEEQEADPSIRIT...,0.655751,82.356804,8.024664
1,0.948766,0.847054,/content/sample01/self_consistency/esmf/sample...,"T=0.1, sample=2, score=1.0154, global_score=1....",KLIEEEYEKEFDDDPETARKKRVEYTREKFEELWKEKEKDPSIEIT...,0.841391,90.123375,2.540517
2,0.927059,1.066167,/content/sample01/self_consistency/esmf/sample...,"T=0.1, sample=3, score=1.0557, global_score=1....",KYIEKEYYVEYDDDPEEARKKRVEDAREKLEELLKEKEEDPSIKIE...,0.660154,77.856621,7.017928

In [ ]:
pdb_path = "/content/test01"
sc_output_dir = os.path.join(pdb_path, "self_consistency")
os.makedirs(sc_output_dir, exist_ok=True)
sc_results = EvalModel.calc_designability(sc_output_dir, pdb_path)
sc_results

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

,tm_score,bb_rmsd,sample_path,header,sequence,ptm,plddt,pae
0,0.672062,6.006414,/content/test01/self_consistency/esmf/sample_1...,"T=0.1, sample=1, score=1.0735, global_score=1....",ERVEEEYRVVYDDDPATARAKAVADAAATLERLWEEQEADPSIRIT...,0.655751,82.356804,8.024664
1,0.948766,0.847054,/content/test01/self_consistency/esmf/sample_2...,"T=0.1, sample=2, score=1.0154, global_score=1....",KLIEEEYEKEFDDDPETARKKRVEYTREKFEELWKEKEKDPSIEIT...,0.841391,90.123375,2.540517
2,0.927059,1.066167,/content/test01/self_consistency/esmf/sample_3...,"T=0.1, sample=3, score=1.0557, global_score=1....",KYIEKEYYVEYDDDPEEARKKRVEDAREKLEELLKEKEEDPSIKIE...,0.660154,77.856621,7.017928

## DEFAULT

###RMSD DEFAULT LENGTH 90-99

In [ ]:
!unzip -q /content/default_90_99.zip -d /content

In [ ]:
root = "/content/default_90_99"

for length in sorted(os.listdir(root)):
    length_path = os.path.join(root, length)
    if not os.path.isdir(length_path):
        continue
    for sample in sorted(os.listdir(length_path)):
        sample_path = os.path.join(length_path, sample)
        if not os.path.isdir(sample_path):
            continue
        sc_output_dir = os.path.join(sample_path, "self_consistency")
        os.makedirs(sc_output_dir, exist_ok=True)
        sc_results = EvalModel.calc_designability(sc_output_dir, sample_path)
        print(f"{length}/{sample} done")

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_090/sample_0 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_090/sample_1 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_090/sample_2 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_090/sample_3 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_090/sample_4 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_090/sample_5 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_090/sample_6 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_090/sample_7 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_090/sample_8 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_090/sample_9 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_091/sample_0 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_091/sample_1 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_091/sample_2 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_091/sample_3 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_091/sample_4 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_091/sample_5 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_091/sample_6 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_091/sample_7 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_091/sample_8 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_091/sample_9 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_092/sample_0 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_092/sample_1 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_092/sample_2 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_092/sample_3 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_092/sample_4 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_092/sample_5 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_092/sample_6 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_092/sample_7 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_092/sample_8 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_092/sample_9 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_093/sample_0 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_093/sample_1 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_093/sample_2 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_093/sample_3 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_093/sample_4 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_093/sample_5 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_093/sample_6 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_093/sample_7 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_093/sample_8 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_093/sample_9 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_094/sample_0 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_094/sample_1 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_094/sample_2 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_094/sample_3 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_094/sample_4 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_094/sample_5 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_094/sample_6 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_094/sample_7 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_094/sample_8 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_094/sample_9 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_095/sample_0 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_095/sample_1 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_095/sample_2 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_095/sample_3 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_095/sample_4 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_095/sample_5 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_095/sample_6 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_095/sample_7 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_095/sample_8 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_095/sample_9 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_096/sample_0 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_096/sample_1 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_096/sample_2 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_096/sample_3 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_096/sample_4 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_096/sample_5 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_096/sample_6 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_096/sample_7 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_096/sample_8 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_096/sample_9 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_097/sample_0 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_097/sample_1 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_097/sample_2 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_097/sample_3 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_097/sample_4 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_097/sample_5 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_097/sample_6 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_097/sample_7 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_097/sample_8 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_097/sample_9 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_098/sample_0 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_098/sample_1 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_098/sample_2 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_098/sample_3 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_098/sample_4 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_098/sample_5 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_098/sample_6 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_098/sample_7 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_098/sample_8 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_098/sample_9 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_099/sample_0 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_099/sample_1 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_099/sample_2 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_099/sample_3 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_099/sample_4 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_099/sample_5 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_099/sample_6 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_099/sample_7 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_099/sample_8 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]
/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

len_099/sample_9 done

/content/CS598-GBL/protein/openfold/utils/tensor_utils.py:79: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  return data[ranges]

In [ ]:
import warnings
warnings.filterwarnings(
    "ignore",
    message="Using a non-tuple sequence for multidimensional indexing is deprecated.*",
    category=UserWarning,
    module=r".*tensor_utils"
)

In [ ]:
from google.colab import files

In [ ]:
rows = []
for root, dirs, filenames in os.walk("/content/default_90_99"):
    for filename in filenames:
        if filename == "sc_results.csv":
            path = os.path.join(root, filename)
            df = pd.read_csv(path)
            parts = root.split("/")
            df["length"] = parts[-3]
            df["sample"] = parts[-2]
            rows.append(df)
combined = pd.concat(rows, ignore_index=True)
combined.to_csv("/content/default_90_99_results.csv", index=False)
files.download("/content/default_90_99_results.csv")

In [ ]:
combined.shape

(300, 11)

### RMSD DEFAULT REST

In [ ]:
!unzip -q /content/default_100_128.zip -d /content

In [ ]:
root = "/content/default_100_128"

for length in sorted(os.listdir(root)):
    length_path = os.path.join(root, length)
    if not os.path.isdir(length_path):
        continue
    for sample in sorted(os.listdir(length_path)):
        sample_path = os.path.join(length_path, sample)
        if not os.path.isdir(sample_path):
            continue
        sc_output_dir = os.path.join(sample_path, "self_consistency")
        os.makedirs(sc_output_dir, exist_ok=True)
        sc_results = EvalModel.calc_designability(sc_output_dir, sample_path)
        print(f"{length}/{sample} done")

len_100/sample_0 done
len_100/sample_1 done
len_100/sample_2 done
len_100/sample_3 done
len_100/sample_4 done
len_100/sample_5 done
len_100/sample_6 done
len_100/sample_7 done
len_100/sample_8 done
len_100/sample_9 done
len_101/sample_0 done
len_101/sample_1 done
len_101/sample_2 done
len_101/sample_3 done
len_101/sample_4 done
len_101/sample_5 done
len_101/sample_6 done
len_101/sample_7 done
len_101/sample_8 done
len_101/sample_9 done
len_102/sample_0 done
len_102/sample_1 done
len_102/sample_2 done
len_102/sample_3 done
len_102/sample_4 done
len_102/sample_5 done
len_102/sample_6 done
len_102/sample_7 done
len_102/sample_8 done
len_102/sample_9 done
len_103/sample_0 done
len_103/sample_1 done
len_103/sample_2 done
len_103/sample_3 done
len_103/sample_4 done
len_103/sample_5 done
len_103/sample_6 done
len_103/sample_7 done
len_103/sample_8 done
len_103/sample_9 done
len_104/sample_0 done
len_104/sample_1 done
len_104/sample_2 done
len_104/sample_3 done
len_104/sample_4 done
len_104/sample_5 done
len_104/sample_6 done
len_104/sample_7 done
len_104/sample_8 done
len_104/sample_9 done
len_105/sample_0 done
len_105/sample_1 done
len_105/sample_2 done
len_105/sample_3 done
len_105/sample_4 done
len_105/sample_5 done
len_105/sample_6 done
len_105/sample_7 done
len_105/sample_8 done
len_105/sample_9 done
len_106/sample_0 done
len_106/sample_1 done
len_106/sample_2 done
len_106/sample_3 done
len_106/sample_4 done
len_106/sample_5 done
len_106/sample_6 done
len_106/sample_7 done
len_106/sample_8 done
len_106/sample_9 done
len_107/sample_0 done
len_107/sample_1 done
len_107/sample_2 done
len_107/sample_3 done
len_107/sample_4 done
len_107/sample_5 done
len_107/sample_6 done
len_107/sample_7 done
len_107/sample_8 done
len_107/sample_9 done
len_108/sample_0 done
len_108/sample_1 done
len_108/sample_2 done
len_108/sample_3 done
len_108/sample_4 done
len_108/sample_5 done
len_108/sample_6 done
len_108/sample_7 done
len_108/sample_8 done
len_108/sample_9 done
len_109/sample_0 done
len_109/sample_1 done
len_109/sample_2 done
len_109/sample_3 done
len_109/sample_4 done
len_109/sample_5 done
len_109/sample_6 done
len_109/sample_7 done
len_109/sample_8 done
len_109/sample_9 done
len_110/sample_0 done
len_110/sample_1 done
len_110/sample_2 done
len_110/sample_3 done
len_110/sample_4 done
len_110/sample_5 done
len_110/sample_6 done
len_110/sample_7 done
len_110/sample_8 done
len_110/sample_9 done
len_111/sample_0 done
len_111/sample_1 done
len_111/sample_2 done
len_111/sample_3 done
len_111/sample_4 done
len_111/sample_5 done
len_111/sample_6 done
len_111/sample_7 done
len_111/sample_8 done
len_111/sample_9 done
len_112/sample_0 done
len_112/sample_1 done
len_112/sample_2 done
len_112/sample_3 done
len_112/sample_4 done
len_112/sample_5 done
len_112/sample_6 done
len_112/sample_7 done
len_112/sample_8 done
len_112/sample_9 done
len_113/sample_0 done
len_113/sample_1 done
len_113/sample_2 done
len_113/sample_3 done
len_113/sample_4 done
len_113/sample_5 done
len_113/sample_6 done
len_113/sample_7 done
len_113/sample_8 done
len_113/sample_9 done
len_114/sample_0 done
len_114/sample_1 done
len_114/sample_2 done
len_114/sample_3 done
len_114/sample_4 done
len_114/sample_5 done
len_114/sample_6 done
len_114/sample_7 done
len_114/sample_8 done
len_114/sample_9 done
len_115/sample_0 done
len_115/sample_1 done
len_115/sample_2 done
len_115/sample_3 done
len_115/sample_4 done
len_115/sample_5 done
len_115/sample_6 done
len_115/sample_7 done
len_115/sample_8 done
len_115/sample_9 done
len_116/sample_0 done
len_116/sample_1 done
len_116/sample_2 done
len_116/sample_3 done
len_116/sample_4 done
len_116/sample_5 done
len_116/sample_6 done
len_116/sample_7 done
len_116/sample_8 done
len_116/sample_9 done
len_117/sample_0 done
len_117/sample_1 done
len_117/sample_2 done
len_117/sample_3 done
len_117/sample_4 done
len_117/sample_5 done
len_117/sample_6 done
len_117/sample_7 done
len_117/sample_8 done
len_117/sample_9 done
len_118/sample_0 done
len_118/sample_1 done
len_118/sample_2 done
len_118/sample_3 done
len_118/sample_4 done
len_118/sample_5 done
len_118/sample_6 done
len_118/sample_7 done
len_118/sample_8 done
len_118/sample_9 done
len_119/sample_0 done
len_119/sample_1 done
len_119/sample_2 done
len_119/sample_3 done
len_119/sample_4 done
len_119/sample_5 done
len_119/sample_6 done
len_119/sample_7 done
len_119/sample_8 done
len_119/sample_9 done
len_120/sample_0 done
len_120/sample_1 done
len_120/sample_2 done
len_120/sample_3 done
len_120/sample_4 done
len_120/sample_5 done
len_120/sample_6 done
len_120/sample_7 done
len_120/sample_8 done
len_120/sample_9 done
len_121/sample_0 done
len_121/sample_1 done
len_121/sample_2 done
len_121/sample_3 done
len_121/sample_4 done
len_121/sample_5 done
len_121/sample_6 done
len_121/sample_7 done
len_121/sample_8 done
len_121/sample_9 done
len_122/sample_0 done
len_122/sample_1 done
len_122/sample_2 done
len_122/sample_3 done
len_122/sample_4 done
len_122/sample_5 done
len_122/sample_6 done
len_122/sample_7 done
len_122/sample_8 done
len_122/sample_9 done
len_123/sample_0 done
len_123/sample_1 done
len_123/sample_2 done
len_123/sample_3 done
len_123/sample_4 done
len_123/sample_5 done
len_123/sample_6 done
len_123/sample_7 done
len_123/sample_8 done
len_123/sample_9 done
len_124/sample_0 done
len_124/sample_1 done
len_124/sample_2 done
len_124/sample_3 done
len_124/sample_4 done
len_124/sample_5 done
len_124/sample_6 done
len_124/sample_7 done
len_124/sample_8 done
len_124/sample_9 done
len_125/sample_0 done
len_125/sample_1 done
len_125/sample_2 done
len_125/sample_3 done
len_125/sample_4 done
len_125/sample_5 done
len_125/sample_6 done
len_125/sample_7 done
len_125/sample_8 done
len_125/sample_9 done
len_126/sample_0 done
len_126/sample_1 done
len_126/sample_2 done
len_126/sample_3 done
len_126/sample_4 done
len_126/sample_5 done
len_126/sample_6 done
len_126/sample_7 done
len_126/sample_8 done
len_126/sample_9 done
len_127/sample_0 done
len_127/sample_1 done
len_127/sample_2 done
len_127/sample_3 done
len_127/sample_4 done
len_127/sample_5 done
len_127/sample_6 done
len_127/sample_7 done
len_127/sample_8 done
len_127/sample_9 done
len_128/sample_0 done
len_128/sample_1 done
len_128/sample_2 done
len_128/sample_3 done
len_128/sample_4 done
len_128/sample_5 done
len_128/sample_6 done
len_128/sample_7 done
len_128/sample_8 done
len_128/sample_9 done

In [ ]:
rows = []
for root, dirs, filenames in os.walk("/content/default_100_128"):
    for filename in filenames:
        if filename == "sc_results.csv":
            path = os.path.join(root, filename)
            df = pd.read_csv(path)
            parts = root.split("/")
            df["length"] = parts[-3]
            df["sample"] = parts[-2]
            rows.append(df)
combined2 = pd.concat(rows, ignore_index=True)
combined2.to_csv("/content/default_100_128_results.csv", index=False)
files.download("/content/default_100_128_results.csv")

In [ ]:
combined_all = pd.concat([combined, combined2], ignore_index=True)
combined_all.to_csv("/content/rmsd_default_results.csv", index=False)
files.download("/content/rmsd_default_results.csv")

## RMSD very_low_noise

In [ ]:
!unzip -q /content/very_low_noise.zip -d /content

In [ ]:
root = "/content/very_low_noise_cleaned"

for length in sorted(os.listdir(root)):
    length_path = os.path.join(root, length)
    if not os.path.isdir(length_path):
        continue
    for sample in sorted(os.listdir(length_path)):
        sample_path = os.path.join(length_path, sample)
        if not os.path.isdir(sample_path):
            continue
        sc_output_dir = os.path.join(sample_path, "self_consistency")
        os.makedirs(sc_output_dir, exist_ok=True)
        sc_results = EvalModel.calc_designability(sc_output_dir, sample_path)
        print(f"{length}/{sample} done")

len_090/sample_0 done
len_090/sample_1 done
len_090/sample_2 done
len_090/sample_3 done
len_090/sample_4 done
len_090/sample_5 done
len_090/sample_6 done
len_090/sample_7 done
len_090/sample_8 done
len_090/sample_9 done
len_091/sample_0 done
len_091/sample_1 done
len_091/sample_2 done
len_091/sample_3 done
len_091/sample_4 done
len_091/sample_5 done
len_091/sample_6 done
len_091/sample_7 done
len_091/sample_8 done
len_091/sample_9 done
len_092/sample_0 done
len_092/sample_1 done
len_092/sample_2 done
len_092/sample_3 done
len_092/sample_4 done
len_092/sample_5 done
len_092/sample_6 done
len_092/sample_7 done
len_092/sample_8 done
len_092/sample_9 done
len_093/sample_0 done
len_093/sample_1 done
len_093/sample_2 done
len_093/sample_3 done
len_093/sample_4 done
len_093/sample_5 done
len_093/sample_6 done
len_093/sample_7 done
len_093/sample_8 done
len_093/sample_9 done
len_094/sample_0 done
len_094/sample_1 done
len_094/sample_2 done
len_094/sample_3 done
len_094/sample_4 done
len_094/sample_5 done
len_094/sample_6 done
len_094/sample_7 done
len_094/sample_8 done
len_094/sample_9 done
len_095/sample_0 done
len_095/sample_1 done
len_095/sample_2 done
len_095/sample_3 done
len_095/sample_4 done
len_095/sample_5 done
len_095/sample_6 done
len_095/sample_7 done
len_095/sample_8 done
len_095/sample_9 done
len_096/sample_0 done
len_096/sample_1 done
len_096/sample_2 done
len_096/sample_3 done
len_096/sample_4 done
len_096/sample_5 done
len_096/sample_6 done
len_096/sample_7 done
len_096/sample_8 done
len_096/sample_9 done
len_097/sample_0 done
len_097/sample_1 done
len_097/sample_2 done
len_097/sample_3 done
len_097/sample_4 done
len_097/sample_5 done
len_097/sample_6 done
len_097/sample_7 done
len_097/sample_8 done
len_097/sample_9 done
len_098/sample_0 done
len_098/sample_1 done
len_098/sample_2 done
len_098/sample_3 done
len_098/sample_4 done
len_098/sample_5 done
len_098/sample_6 done
len_098/sample_7 done
len_098/sample_8 done
len_098/sample_9 done
len_099/sample_0 done
len_099/sample_1 done
len_099/sample_2 done
len_099/sample_3 done
len_099/sample_4 done
len_099/sample_5 done
len_099/sample_6 done
len_099/sample_7 done
len_099/sample_8 done
len_099/sample_9 done
len_100/sample_0 done
len_100/sample_1 done
len_100/sample_2 done
len_100/sample_3 done
len_100/sample_4 done
len_100/sample_5 done
len_100/sample_6 done
len_100/sample_7 done
len_100/sample_8 done
len_100/sample_9 done
len_101/sample_0 done
len_101/sample_1 done
len_101/sample_2 done
len_101/sample_3 done
len_101/sample_4 done
len_101/sample_5 done
len_101/sample_6 done
len_101/sample_7 done
len_101/sample_8 done
len_101/sample_9 done
len_102/sample_0 done
len_102/sample_1 done
len_102/sample_2 done
len_102/sample_3 done
len_102/sample_4 done
len_102/sample_5 done
len_102/sample_6 done
len_102/sample_7 done
len_102/sample_8 done
len_102/sample_9 done
len_103/sample_0 done
len_103/sample_1 done
len_103/sample_2 done
len_103/sample_3 done
len_103/sample_4 done
len_103/sample_5 done
len_103/sample_6 done
len_103/sample_7 done
len_103/sample_8 done
len_103/sample_9 done
len_104/sample_0 done
len_104/sample_1 done
len_104/sample_2 done
len_104/sample_3 done
len_104/sample_4 done
len_104/sample_5 done
len_104/sample_6 done
len_104/sample_7 done
len_104/sample_8 done
len_104/sample_9 done
len_105/sample_0 done
len_105/sample_1 done
len_105/sample_2 done
len_105/sample_3 done
len_105/sample_4 done
len_105/sample_5 done
len_105/sample_6 done
len_105/sample_7 done
len_105/sample_8 done
len_105/sample_9 done
len_106/sample_0 done
len_106/sample_1 done
len_106/sample_2 done
len_106/sample_3 done
len_106/sample_4 done
len_106/sample_5 done
len_106/sample_6 done
len_106/sample_7 done
len_106/sample_8 done
len_106/sample_9 done
len_107/sample_0 done
len_107/sample_1 done
len_107/sample_2 done
len_107/sample_3 done
len_107/sample_4 done
len_107/sample_5 done
len_107/sample_6 done
len_107/sample_7 done
len_107/sample_8 done
len_107/sample_9 done
len_108/sample_0 done
len_108/sample_1 done
len_108/sample_2 done
len_108/sample_3 done
len_108/sample_4 done
len_108/sample_5 done
len_108/sample_6 done
len_108/sample_7 done
len_108/sample_8 done
len_108/sample_9 done
len_109/sample_0 done
len_109/sample_1 done
len_109/sample_2 done
len_109/sample_3 done
len_109/sample_4 done
len_109/sample_5 done
len_109/sample_6 done
len_109/sample_7 done
len_109/sample_8 done
len_109/sample_9 done
len_110/sample_0 done
len_110/sample_1 done
len_110/sample_2 done
len_110/sample_3 done
len_110/sample_4 done
len_110/sample_5 done
len_110/sample_6 done
len_110/sample_7 done
len_110/sample_8 done
len_110/sample_9 done
len_111/sample_0 done
len_111/sample_1 done
len_111/sample_2 done
len_111/sample_3 done
len_111/sample_4 done
len_111/sample_5 done
len_111/sample_6 done
len_111/sample_7 done
len_111/sample_8 done
len_111/sample_9 done
len_112/sample_0 done
len_112/sample_1 done
len_112/sample_2 done
len_112/sample_3 done
len_112/sample_4 done
len_112/sample_5 done
len_112/sample_6 done
len_112/sample_7 done
len_112/sample_8 done
len_112/sample_9 done
len_113/sample_0 done
len_113/sample_1 done
len_113/sample_2 done
len_113/sample_3 done
len_113/sample_4 done
len_113/sample_5 done
len_113/sample_6 done
len_113/sample_7 done
len_113/sample_8 done
len_113/sample_9 done
len_114/sample_0 done
len_114/sample_1 done
len_114/sample_2 done
len_114/sample_3 done
len_114/sample_4 done
len_114/sample_5 done
len_114/sample_6 done
len_114/sample_7 done
len_114/sample_8 done
len_114/sample_9 done
len_115/sample_0 done
len_115/sample_1 done
len_115/sample_2 done
len_115/sample_3 done
len_115/sample_4 done
len_115/sample_5 done
len_115/sample_6 done
len_115/sample_7 done
len_115/sample_8 done
len_115/sample_9 done
len_116/sample_0 done
len_116/sample_1 done
len_116/sample_2 done
len_116/sample_3 done
len_116/sample_4 done
len_116/sample_5 done
len_116/sample_6 done
len_116/sample_7 done
len_116/sample_8 done
len_116/sample_9 done
len_117/sample_0 done
len_117/sample_1 done
len_117/sample_2 done
len_117/sample_3 done
len_117/sample_4 done
len_117/sample_5 done
len_117/sample_6 done
len_117/sample_7 done
len_117/sample_8 done
len_117/sample_9 done
len_118/sample_0 done
len_118/sample_1 done
len_118/sample_2 done
len_118/sample_3 done
len_118/sample_4 done
len_118/sample_5 done
len_118/sample_6 done
len_118/sample_7 done
len_118/sample_8 done
len_118/sample_9 done
len_119/sample_0 done
len_119/sample_1 done
len_119/sample_2 done
len_119/sample_3 done
len_119/sample_4 done
len_119/sample_5 done
len_119/sample_6 done
len_119/sample_7 done
len_119/sample_8 done
len_119/sample_9 done
len_120/sample_0 done
len_120/sample_1 done
len_120/sample_2 done
len_120/sample_3 done
len_120/sample_4 done
len_120/sample_5 done
len_120/sample_6 done
len_120/sample_7 done
len_120/sample_8 done
len_120/sample_9 done
len_121/sample_0 done
len_121/sample_1 done
len_121/sample_2 done
len_121/sample_3 done
len_121/sample_4 done
len_121/sample_5 done
len_121/sample_6 done
len_121/sample_7 done
len_121/sample_8 done
len_121/sample_9 done
len_122/sample_0 done
len_122/sample_1 done
len_122/sample_2 done
len_122/sample_3 done
len_122/sample_4 done
len_122/sample_5 done
len_122/sample_6 done
len_122/sample_7 done
len_122/sample_8 done
len_122/sample_9 done
len_123/sample_0 done
len_123/sample_1 done
len_123/sample_2 done
len_123/sample_3 done
len_123/sample_4 done
len_123/sample_5 done
len_123/sample_6 done
len_123/sample_7 done
len_123/sample_8 done
len_123/sample_9 done
len_124/sample_0 done
len_124/sample_1 done
len_124/sample_2 done
len_124/sample_3 done
len_124/sample_4 done
len_124/sample_5 done
len_124/sample_6 done
len_124/sample_7 done
len_124/sample_8 done
len_124/sample_9 done
len_125/sample_0 done
len_125/sample_1 done
len_125/sample_2 done
len_125/sample_3 done
len_125/sample_4 done
len_125/sample_5 done
len_125/sample_6 done
len_125/sample_7 done
len_125/sample_8 done
len_125/sample_9 done
len_126/sample_0 done
len_126/sample_1 done
len_126/sample_2 done
len_126/sample_3 done
len_126/sample_4 done
len_126/sample_5 done
len_126/sample_6 done
len_126/sample_7 done
len_126/sample_8 done
len_126/sample_9 done
len_127/sample_0 done
len_127/sample_1 done
len_127/sample_2 done
len_127/sample_3 done
len_127/sample_4 done
len_127/sample_5 done
len_127/sample_6 done
len_127/sample_7 done
len_127/sample_8 done
len_127/sample_9 done
len_128/sample_0 done
len_128/sample_1 done
len_128/sample_2 done
len_128/sample_3 done
len_128/sample_4 done
len_128/sample_5 done
len_128/sample_6 done
len_128/sample_7 done
len_128/sample_8 done
len_128/sample_9 done

In [ ]:
rows = []
for root, dirs, filenames in os.walk("/content/very_low_noise_cleaned"):
    for filename in filenames:
        if filename == "sc_results.csv":
            path = os.path.join(root, filename)
            df = pd.read_csv(path)
            parts = root.split("/")
            df["length"] = parts[-3]
            df["sample"] = parts[-2]
            rows.append(df)
very_low_noise = pd.concat(rows, ignore_index=True)
very_low_noise.to_csv("/content/rmsd_very_low_noise_results.csv", index=False)
files.download("/content/rmsd_very_low_noise_results.csv")

## Fast

In [ ]:
!unzip -q /content/fast_cleaned.zip -d /content

In [ ]:
root = "/content/fast_cleaned"

for length in sorted(os.listdir(root)):
    length_path = os.path.join(root, length)
    if not os.path.isdir(length_path):
        continue
    for sample in sorted(os.listdir(length_path)):
        sample_path = os.path.join(length_path, sample)
        if not os.path.isdir(sample_path):
            continue
        sc_output_dir = os.path.join(sample_path, "self_consistency")
        os.makedirs(sc_output_dir, exist_ok=True)
        sc_results = EvalModel.calc_designability(sc_output_dir, sample_path)
        print(f"{length}/{sample} done")

len_090/sample_0 done
len_090/sample_1 done
len_090/sample_2 done
len_090/sample_3 done
len_090/sample_4 done
len_090/sample_5 done
len_090/sample_6 done
len_090/sample_7 done
len_090/sample_8 done
len_090/sample_9 done
len_091/sample_0 done
len_091/sample_1 done
len_091/sample_2 done
len_091/sample_3 done
len_091/sample_4 done
len_091/sample_5 done
len_091/sample_6 done
len_091/sample_7 done
len_091/sample_8 done
len_091/sample_9 done
len_092/sample_0 done
len_092/sample_1 done
len_092/sample_2 done
len_092/sample_3 done
len_092/sample_4 done
len_092/sample_5 done
len_092/sample_6 done
len_092/sample_7 done
len_092/sample_8 done
len_092/sample_9 done
len_093/sample_0 done
len_093/sample_1 done
len_093/sample_2 done
len_093/sample_3 done
len_093/sample_4 done
len_093/sample_5 done
len_093/sample_6 done
len_093/sample_7 done
len_093/sample_8 done
len_093/sample_9 done
len_094/sample_0 done
len_094/sample_1 done
len_094/sample_2 done
len_094/sample_3 done
len_094/sample_4 done
len_094/sample_5 done
len_094/sample_6 done
len_094/sample_7 done
len_094/sample_8 done
len_094/sample_9 done
len_095/sample_0 done
len_095/sample_1 done
len_095/sample_2 done
len_095/sample_3 done
len_095/sample_4 done
len_095/sample_5 done
len_095/sample_6 done
len_095/sample_7 done
len_095/sample_8 done
len_095/sample_9 done
len_096/sample_0 done
len_096/sample_1 done
len_096/sample_2 done
len_096/sample_3 done
len_096/sample_4 done
len_096/sample_5 done
len_096/sample_6 done
len_096/sample_7 done
len_096/sample_8 done
len_096/sample_9 done
len_097/sample_0 done
len_097/sample_1 done
len_097/sample_2 done
len_097/sample_3 done
len_097/sample_4 done
len_097/sample_5 done
len_097/sample_6 done
len_097/sample_7 done
len_097/sample_8 done
len_097/sample_9 done
len_098/sample_0 done
len_098/sample_1 done
len_098/sample_2 done
len_098/sample_3 done
len_098/sample_4 done
len_098/sample_5 done
len_098/sample_6 done
len_098/sample_7 done
len_098/sample_8 done
len_098/sample_9 done
len_099/sample_0 done
len_099/sample_1 done
len_099/sample_2 done
len_099/sample_3 done
len_099/sample_4 done
len_099/sample_5 done
len_099/sample_6 done
len_099/sample_7 done
len_099/sample_8 done
len_099/sample_9 done
len_100/sample_0 done
len_100/sample_1 done
len_100/sample_2 done
len_100/sample_3 done
len_100/sample_4 done
len_100/sample_5 done
len_100/sample_6 done
len_100/sample_7 done
len_100/sample_8 done
len_100/sample_9 done
len_101/sample_0 done
len_101/sample_1 done
len_101/sample_2 done
len_101/sample_3 done
len_101/sample_4 done
len_101/sample_5 done
len_101/sample_6 done
len_101/sample_7 done
len_101/sample_8 done
len_101/sample_9 done
len_102/sample_0 done
len_102/sample_1 done
len_102/sample_2 done
len_102/sample_3 done
len_102/sample_4 done
len_102/sample_5 done
len_102/sample_6 done
len_102/sample_7 done
len_102/sample_8 done
len_102/sample_9 done
len_103/sample_0 done
len_103/sample_1 done
len_103/sample_2 done
len_103/sample_3 done
len_103/sample_4 done
len_103/sample_5 done
len_103/sample_6 done
len_103/sample_7 done
len_103/sample_8 done
len_103/sample_9 done
len_104/sample_0 done
len_104/sample_1 done
len_104/sample_2 done
len_104/sample_3 done
len_104/sample_4 done
len_104/sample_5 done
len_104/sample_6 done
len_104/sample_7 done
len_104/sample_8 done
len_104/sample_9 done
len_105/sample_0 done
len_105/sample_1 done
len_105/sample_2 done
len_105/sample_3 done
len_105/sample_4 done
len_105/sample_5 done
len_105/sample_6 done
len_105/sample_7 done
len_105/sample_8 done
len_105/sample_9 done
len_106/sample_0 done
len_106/sample_1 done
len_106/sample_2 done
len_106/sample_3 done
len_106/sample_4 done
len_106/sample_5 done
len_106/sample_6 done
len_106/sample_7 done
len_106/sample_8 done
len_106/sample_9 done
len_107/sample_0 done
len_107/sample_1 done
len_107/sample_2 done
len_107/sample_3 done
len_107/sample_4 done
len_107/sample_5 done
len_107/sample_6 done
len_107/sample_7 done
len_107/sample_8 done
len_107/sample_9 done
len_108/sample_0 done
len_108/sample_1 done
len_108/sample_2 done
len_108/sample_3 done
len_108/sample_4 done
len_108/sample_5 done
len_108/sample_6 done
len_108/sample_7 done
len_108/sample_8 done
len_108/sample_9 done
len_109/sample_0 done
len_109/sample_1 done
len_109/sample_2 done
len_109/sample_3 done
len_109/sample_4 done
len_109/sample_5 done
len_109/sample_6 done
len_109/sample_7 done
len_109/sample_8 done
len_109/sample_9 done
len_110/sample_0 done
len_110/sample_1 done
len_110/sample_2 done
len_110/sample_3 done
len_110/sample_4 done
len_110/sample_5 done
len_110/sample_6 done
len_110/sample_7 done
len_110/sample_8 done
len_110/sample_9 done
len_111/sample_0 done
len_111/sample_1 done
len_111/sample_2 done
len_111/sample_3 done
len_111/sample_4 done
len_111/sample_5 done
len_111/sample_6 done
len_111/sample_7 done
len_111/sample_8 done
len_111/sample_9 done
len_112/sample_0 done
len_112/sample_1 done
len_112/sample_2 done
len_112/sample_3 done
len_112/sample_4 done
len_112/sample_5 done
len_112/sample_6 done
len_112/sample_7 done
len_112/sample_8 done
len_112/sample_9 done
len_113/sample_0 done
len_113/sample_1 done
len_113/sample_2 done
len_113/sample_3 done
len_113/sample_4 done
len_113/sample_5 done
len_113/sample_6 done
len_113/sample_7 done
len_113/sample_8 done
len_113/sample_9 done
len_114/sample_0 done
len_114/sample_1 done
len_114/sample_2 done
len_114/sample_3 done
len_114/sample_4 done
len_114/sample_5 done
len_114/sample_6 done
len_114/sample_7 done
len_114/sample_8 done
len_114/sample_9 done
len_115/sample_0 done
len_115/sample_1 done
len_115/sample_2 done
len_115/sample_3 done
len_115/sample_4 done
len_115/sample_5 done
len_115/sample_6 done
len_115/sample_7 done
len_115/sample_8 done
len_115/sample_9 done
len_116/sample_0 done
len_116/sample_1 done
len_116/sample_2 done
len_116/sample_3 done
len_116/sample_4 done
len_116/sample_5 done
len_116/sample_6 done
len_116/sample_7 done
len_116/sample_8 done
len_116/sample_9 done
len_117/sample_0 done
len_117/sample_1 done
len_117/sample_2 done
len_117/sample_3 done
len_117/sample_4 done
len_117/sample_5 done
len_117/sample_6 done
len_117/sample_7 done
len_117/sample_8 done
len_117/sample_9 done
len_118/sample_0 done
len_118/sample_1 done
len_118/sample_2 done
len_118/sample_3 done
len_118/sample_4 done
len_118/sample_5 done
len_118/sample_6 done
len_118/sample_7 done
len_118/sample_8 done
len_118/sample_9 done
len_119/sample_0 done
len_119/sample_1 done
len_119/sample_2 done
len_119/sample_3 done
len_119/sample_4 done
len_119/sample_5 done
len_119/sample_6 done
len_119/sample_7 done
len_119/sample_8 done
len_119/sample_9 done
len_120/sample_0 done
len_120/sample_1 done
len_120/sample_2 done
len_120/sample_3 done
len_120/sample_4 done
len_120/sample_5 done
len_120/sample_6 done
len_120/sample_7 done
len_120/sample_8 done
len_120/sample_9 done
len_121/sample_0 done
len_121/sample_1 done
len_121/sample_2 done
len_121/sample_3 done
len_121/sample_4 done
len_121/sample_5 done
len_121/sample_6 done
len_121/sample_7 done
len_121/sample_8 done
len_121/sample_9 done
len_122/sample_0 done
len_122/sample_1 done
len_122/sample_2 done
len_122/sample_3 done
len_122/sample_4 done
len_122/sample_5 done
len_122/sample_6 done
len_122/sample_7 done
len_122/sample_8 done
len_122/sample_9 done
len_123/sample_0 done
len_123/sample_1 done
len_123/sample_2 done
len_123/sample_3 done
len_123/sample_4 done
len_123/sample_5 done
len_123/sample_6 done
len_123/sample_7 done
len_123/sample_8 done
len_123/sample_9 done
len_124/sample_0 done
len_124/sample_1 done
len_124/sample_2 done
len_124/sample_3 done
len_124/sample_4 done
len_124/sample_5 done
len_124/sample_6 done
len_124/sample_7 done
len_124/sample_8 done
len_124/sample_9 done
len_125/sample_0 done
len_125/sample_1 done
len_125/sample_2 done
len_125/sample_3 done
len_125/sample_4 done
len_125/sample_5 done
len_125/sample_6 done
len_125/sample_7 done
len_125/sample_8 done
len_125/sample_9 done
len_126/sample_0 done
len_126/sample_1 done
len_126/sample_2 done
len_126/sample_3 done
len_126/sample_4 done
len_126/sample_5 done
len_126/sample_6 done
len_126/sample_7 done
len_126/sample_8 done
len_126/sample_9 done
len_127/sample_0 done
len_127/sample_1 done
len_127/sample_2 done
len_127/sample_3 done
len_127/sample_4 done
len_127/sample_5 done
len_127/sample_6 done
len_127/sample_7 done
len_127/sample_8 done
len_127/sample_9 done
len_128/sample_0 done
len_128/sample_1 done
len_128/sample_2 done
len_128/sample_3 done
len_128/sample_4 done
len_128/sample_5 done
len_128/sample_6 done
len_128/sample_7 done
len_128/sample_8 done
len_128/sample_9 done

In [ ]:
rows = []
for root, dirs, filenames in os.walk("/content/fast_cleaned"):
    for filename in filenames:
        if filename == "sc_results.csv":
            path = os.path.join(root, filename)
            df = pd.read_csv(path)
            parts = root.split("/")
            df["length"] = parts[-3]
            df["sample"] = parts[-2]
            rows.append(df)
fast = pd.concat(rows, ignore_index=True)
fast.to_csv("/content/rmsd_fast_results.csv", index=False)
files.download("/content/rmsd_fast_results.csv")

In [ ]:
fast.shape

(1170, 11)

#Substructure - all sample

In [ ]:
pdb_path = "/content/CS598-GBL/protein/example_data/length_70/sample_0"
path = os.path.join(pdb_path, "sample.pdb")
sub_ratio = EvalModel.calc_mdtraj_metrics(path)
sub_ratio

{'non_coil_percent': np.float64(0.6571428571428571),
 'coil_percent': np.float64(0.34285714285714286),
 'helix_percent': np.float64(0.34285714285714286),
 'strand_percent': np.float64(0.3142857142857143),
 'radius_of_gyration': np.float64(1.0974538862859071)}

In [ ]:
sub_ratio.items()

dict_items([('non_coil_percent', np.float64(0.6571428571428571)), ('coil_percent', np.float64(0.34285714285714286)), ('helix_percent', np.float64(0.34285714285714286)), ('strand_percent', np.float64(0.3142857142857143)), ('radius_of_gyration', np.float64(1.0974538862859071))])

In [ ]:
!unzip -q /content/default_cleaned.zip -d /content

In [ ]:
root = "/content/default_cleaned"
rows = []
for length in sorted(os.listdir(root)):
    length_path = os.path.join(root, length)
    if not os.path.isdir(length_path):
        continue
    for sample in sorted(os.listdir(length_path)):
        sample_path = os.path.join(length_path, sample)
        if not os.path.isdir(sample_path):
            continue
        pdb_file = os.path.join(sample_path, "sample.pdb")
        sub_ratio = EvalModel.calc_mdtraj_metrics(pdb_file)
        row = {k: float(v) for k, v in sub_ratio.items()}
        row["length"] = length
        row["sample"] = sample
        rows.append(row)
        print(f"{length}/{sample} done")

len_090/sample_0 done
len_090/sample_1 done
len_090/sample_2 done
len_090/sample_3 done
len_090/sample_4 done
len_090/sample_5 done
len_090/sample_6 done
len_090/sample_7 done
len_090/sample_8 done
len_090/sample_9 done
len_091/sample_0 done
len_091/sample_1 done
len_091/sample_2 done
len_091/sample_3 done
len_091/sample_4 done
len_091/sample_5 done
len_091/sample_6 done
len_091/sample_7 done
len_091/sample_8 done
len_091/sample_9 done
len_092/sample_0 done
len_092/sample_1 done
len_092/sample_2 done
len_092/sample_3 done
len_092/sample_4 done
len_092/sample_5 done
len_092/sample_6 done
len_092/sample_7 done
len_092/sample_8 done
len_092/sample_9 done
len_093/sample_0 done
len_093/sample_1 done
len_093/sample_2 done
len_093/sample_3 done
len_093/sample_4 done
len_093/sample_5 done
len_093/sample_6 done
len_093/sample_7 done
len_093/sample_8 done
len_093/sample_9 done
len_094/sample_0 done
len_094/sample_1 done
len_094/sample_2 done
len_094/sample_3 done
len_094/sample_4 done
len_094/sample_5 done
len_094/sample_6 done
len_094/sample_7 done
len_094/sample_8 done
len_094/sample_9 done
len_095/sample_0 done
len_095/sample_1 done
len_095/sample_2 done
len_095/sample_3 done
len_095/sample_4 done
len_095/sample_5 done
len_095/sample_6 done
len_095/sample_7 done
len_095/sample_8 done
len_095/sample_9 done
len_096/sample_0 done
len_096/sample_1 done
len_096/sample_2 done
len_096/sample_3 done
len_096/sample_4 done
len_096/sample_5 done
len_096/sample_6 done
len_096/sample_7 done
len_096/sample_8 done
len_096/sample_9 done
len_097/sample_0 done
len_097/sample_1 done
len_097/sample_2 done
len_097/sample_3 done
len_097/sample_4 done
len_097/sample_5 done
len_097/sample_6 done
len_097/sample_7 done
len_097/sample_8 done
len_097/sample_9 done
len_098/sample_0 done
len_098/sample_1 done
len_098/sample_2 done
len_098/sample_3 done
len_098/sample_4 done
len_098/sample_5 done
len_098/sample_6 done
len_098/sample_7 done
len_098/sample_8 done
len_098/sample_9 done
len_099/sample_0 done
len_099/sample_1 done
len_099/sample_2 done
len_099/sample_3 done
len_099/sample_4 done
len_099/sample_5 done
len_099/sample_6 done
len_099/sample_7 done
len_099/sample_8 done
len_099/sample_9 done
len_100/sample_0 done
len_100/sample_1 done
len_100/sample_2 done
len_100/sample_3 done
len_100/sample_4 done
len_100/sample_5 done
len_100/sample_6 done
len_100/sample_7 done
len_100/sample_8 done
len_100/sample_9 done
len_101/sample_0 done
len_101/sample_1 done
len_101/sample_2 done
len_101/sample_3 done
len_101/sample_4 done
len_101/sample_5 done
len_101/sample_6 done
len_101/sample_7 done
len_101/sample_8 done
len_101/sample_9 done
len_102/sample_0 done
len_102/sample_1 done
len_102/sample_2 done
len_102/sample_3 done
len_102/sample_4 done
len_102/sample_5 done
len_102/sample_6 done
len_102/sample_7 done
len_102/sample_8 done
len_102/sample_9 done
len_103/sample_0 done
len_103/sample_1 done
len_103/sample_2 done
len_103/sample_3 done
len_103/sample_4 done
len_103/sample_5 done
len_103/sample_6 done
len_103/sample_7 done
len_103/sample_8 done
len_103/sample_9 done
len_104/sample_0 done
len_104/sample_1 done
len_104/sample_2 done
len_104/sample_3 done
len_104/sample_4 done
len_104/sample_5 done
len_104/sample_6 done
len_104/sample_7 done
len_104/sample_8 done
len_104/sample_9 done
len_105/sample_0 done
len_105/sample_1 done
len_105/sample_2 done
len_105/sample_3 done
len_105/sample_4 done
len_105/sample_5 done
len_105/sample_6 done
len_105/sample_7 done
len_105/sample_8 done
len_105/sample_9 done
len_106/sample_0 done
len_106/sample_1 done
len_106/sample_2 done
len_106/sample_3 done
len_106/sample_4 done
len_106/sample_5 done
len_106/sample_6 done
len_106/sample_7 done
len_106/sample_8 done
len_106/sample_9 done
len_107/sample_0 done
len_107/sample_1 done
len_107/sample_2 done
len_107/sample_3 done
len_107/sample_4 done
len_107/sample_5 done
len_107/sample_6 done
len_107/sample_7 done
len_107/sample_8 done
len_107/sample_9 done
len_108/sample_0 done
len_108/sample_1 done
len_108/sample_2 done
len_108/sample_3 done
len_108/sample_4 done
len_108/sample_5 done
len_108/sample_6 done
len_108/sample_7 done
len_108/sample_8 done
len_108/sample_9 done
len_109/sample_0 done
len_109/sample_1 done
len_109/sample_2 done
len_109/sample_3 done
len_109/sample_4 done
len_109/sample_5 done
len_109/sample_6 done
len_109/sample_7 done
len_109/sample_8 done
len_109/sample_9 done
len_110/sample_0 done
len_110/sample_1 done
len_110/sample_2 done
len_110/sample_3 done
len_110/sample_4 done
len_110/sample_5 done
len_110/sample_6 done
len_110/sample_7 done
len_110/sample_8 done
len_110/sample_9 done
len_111/sample_0 done
len_111/sample_1 done
len_111/sample_2 done
len_111/sample_3 done
len_111/sample_4 done
len_111/sample_5 done
len_111/sample_6 done
len_111/sample_7 done
len_111/sample_8 done
len_111/sample_9 done
len_112/sample_0 done
len_112/sample_1 done
len_112/sample_2 done
len_112/sample_3 done
len_112/sample_4 done
len_112/sample_5 done
len_112/sample_6 done
len_112/sample_7 done
len_112/sample_8 done
len_112/sample_9 done
len_113/sample_0 done
len_113/sample_1 done
len_113/sample_2 done
len_113/sample_3 done
len_113/sample_4 done
len_113/sample_5 done
len_113/sample_6 done
len_113/sample_7 done
len_113/sample_8 done
len_113/sample_9 done
len_114/sample_0 done
len_114/sample_1 done
len_114/sample_2 done
len_114/sample_3 done
len_114/sample_4 done
len_114/sample_5 done
len_114/sample_6 done
len_114/sample_7 done
len_114/sample_8 done
len_114/sample_9 done
len_115/sample_0 done
len_115/sample_1 done
len_115/sample_2 done
len_115/sample_3 done
len_115/sample_4 done
len_115/sample_5 done
len_115/sample_6 done
len_115/sample_7 done
len_115/sample_8 done
len_115/sample_9 done
len_116/sample_0 done
len_116/sample_1 done
len_116/sample_2 done
len_116/sample_3 done
len_116/sample_4 done
len_116/sample_5 done
len_116/sample_6 done
len_116/sample_7 done
len_116/sample_8 done
len_116/sample_9 done
len_117/sample_0 done
len_117/sample_1 done
len_117/sample_2 done
len_117/sample_3 done
len_117/sample_4 done
len_117/sample_5 done
len_117/sample_6 done
len_117/sample_7 done
len_117/sample_8 done
len_117/sample_9 done
len_118/sample_0 done
len_118/sample_1 done
len_118/sample_2 done
len_118/sample_3 done
len_118/sample_4 done
len_118/sample_5 done
len_118/sample_6 done
len_118/sample_7 done
len_118/sample_8 done
len_118/sample_9 done
len_119/sample_0 done
len_119/sample_1 done
len_119/sample_2 done
len_119/sample_3 done
len_119/sample_4 done
len_119/sample_5 done
len_119/sample_6 done
len_119/sample_7 done
len_119/sample_8 done
len_119/sample_9 done
len_120/sample_0 done
len_120/sample_1 done
len_120/sample_2 done
len_120/sample_3 done
len_120/sample_4 done
len_120/sample_5 done
len_120/sample_6 done
len_120/sample_7 done
len_120/sample_8 done
len_120/sample_9 done
len_121/sample_0 done
len_121/sample_1 done
len_121/sample_2 done
len_121/sample_3 done
len_121/sample_4 done
len_121/sample_5 done
len_121/sample_6 done
len_121/sample_7 done
len_121/sample_8 done
len_121/sample_9 done
len_122/sample_0 done
len_122/sample_1 done
len_122/sample_2 done
len_122/sample_3 done
len_122/sample_4 done
len_122/sample_5 done
len_122/sample_6 done
len_122/sample_7 done
len_122/sample_8 done
len_122/sample_9 done
len_123/sample_0 done
len_123/sample_1 done
len_123/sample_2 done
len_123/sample_3 done
len_123/sample_4 done
len_123/sample_5 done
len_123/sample_6 done
len_123/sample_7 done
len_123/sample_8 done
len_123/sample_9 done
len_124/sample_0 done
len_124/sample_1 done
len_124/sample_2 done
len_124/sample_3 done
len_124/sample_4 done
len_124/sample_5 done
len_124/sample_6 done
len_124/sample_7 done
len_124/sample_8 done
len_124/sample_9 done
len_125/sample_0 done
len_125/sample_1 done
len_125/sample_2 done
len_125/sample_3 done
len_125/sample_4 done
len_125/sample_5 done
len_125/sample_6 done
len_125/sample_7 done
len_125/sample_8 done
len_125/sample_9 done
len_126/sample_0 done
len_126/sample_1 done
len_126/sample_2 done
len_126/sample_3 done
len_126/sample_4 done
len_126/sample_5 done
len_126/sample_6 done
len_126/sample_7 done
len_126/sample_8 done
len_126/sample_9 done
len_127/sample_0 done
len_127/sample_1 done
len_127/sample_2 done
len_127/sample_3 done
len_127/sample_4 done
len_127/sample_5 done
len_127/sample_6 done
len_127/sample_7 done
len_127/sample_8 done
len_127/sample_9 done
len_128/sample_0 done
len_128/sample_1 done
len_128/sample_2 done
len_128/sample_3 done
len_128/sample_4 done
len_128/sample_5 done
len_128/sample_6 done
len_128/sample_7 done
len_128/sample_8 done
len_128/sample_9 done

In [ ]:
df = pd.DataFrame(rows)
df.head(2)

,non_coil_percent,coil_percent,helix_percent,strand_percent,radius_of_gyration,length,sample
0,0.766667,0.233333,0.577778,0.188889,1.292837,len_090,sample_0
1,0.866667,0.133333,0.866667,0.000000,1.356013,len_090,sample_1

In [ ]:
df.shape

(390, 7)

In [ ]:
df.to_csv("/content/substructure_default.csv", index=False)
files.download("/content/substructure_default.csv")

In [ ]:
root = "/content/very_low_noise_cleaned"
rows = []

for length in sorted(os.listdir(root)):
    length_path = os.path.join(root, length)
    if not os.path.isdir(length_path):
        continue
    for sample in sorted(os.listdir(length_path)):
        sample_path = os.path.join(length_path, sample)
        if not os.path.isdir(sample_path):
            continue
        pdb_file = os.path.join(sample_path, "sample.pdb")
        sub_ratio = EvalModel.calc_mdtraj_metrics(pdb_file)
        row = {k: float(v) for k, v in sub_ratio.items()}
        row["length"] = length
        row["sample"] = sample
        rows.append(row)

In [ ]:
df = pd.DataFrame(rows)
df.head(2)

,non_coil_percent,coil_percent,helix_percent,strand_percent,radius_of_gyration,length,sample
0,0.888889,0.111111,0.888889,0.0,1.157034,len_090,sample_0
1,0.877778,0.122222,0.877778,0.0,1.220343,len_090,sample_1

In [ ]:
df.to_csv("/content/substructure_very_low_noise.csv", index=False)
files.download("/content/substructure_very_low_noise.csv")

In [ ]:
root = "/content/fast_cleaned"
rows = []

for length in sorted(os.listdir(root)):
    length_path = os.path.join(root, length)
    if not os.path.isdir(length_path):
        continue
    for sample in sorted(os.listdir(length_path)):
        sample_path = os.path.join(length_path, sample)
        if not os.path.isdir(sample_path):
            continue
        pdb_file = os.path.join(sample_path, "sample.pdb")
        sub_ratio = EvalModel.calc_mdtraj_metrics(pdb_file)
        row = {k: float(v) for k, v in sub_ratio.items()}
        row["length"] = length
        row["sample"] = sample
        rows.append(row)

In [ ]:
df = pd.DataFrame(rows)
df.to_csv("/content/substructure_fast.csv", index=False)
files.download("/content/substructure_fast.csv")

#Clustering

##Default

In [ ]:
!wget https://www.sbg.bio.ic.ac.uk/maxcluster/maxcluster64bit

--2026-04-20 21:29:16--  https://www.sbg.bio.ic.ac.uk/maxcluster/maxcluster64bit
Resolving www.sbg.bio.ic.ac.uk (www.sbg.bio.ic.ac.uk)... 146.179.45.48
Connecting to www.sbg.bio.ic.ac.uk (www.sbg.bio.ic.ac.uk)|146.179.45.48|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3068616 (2.9M)
Saving to: ‘maxcluster64bit.1’

maxcluster64bit.1   100%[===================>]   2.93M  --.-KB/s    in 0.08s

2026-04-20 21:29:16 (34.8 MB/s) - ‘maxcluster64bit.1’ saved [3068616/3068616]

In [ ]:
root = "/content/default_cleaned"
paths = []
for length in sorted(os.listdir(root)):
    length_path = os.path.join(root, length)
    if not os.path.isdir(length_path):
        continue
    for sample in sorted(os.listdir(length_path)):
        sample_path = os.path.join(length_path, sample)
        if os.path.isdir(sample_path):
            paths.append(sample_path + "/")
df = pd.DataFrame(paths)
df.to_csv("/content/default_paths.csv", index=False, header=False)

In [ ]:
pdb_csv_path="/content/default_paths.csv"
pdb_path_list = df[0].tolist()

cluster_dir = os.path.join(Path(pdb_csv_path).parent, "cluster")
os.makedirs(cluster_dir, exist_ok=True)
designable_paths = pdb_path_list
designable_file_path = os.path.join(cluster_dir, "designable_paths.txt")
updated_paths = [os.path.join(path, "sample.pdb") for path in designable_paths]
with open(designable_file_path, "w") as f:
    f.write("\n".join(updated_paths))

print("designable_file_path: ", designable_file_path)
print("cluster_dir: ", cluster_dir)

designable_file_path:  /content/cluster/designable_paths.txt
cluster_dir:  /content/cluster

In [ ]:
designable_file_path = "/content/cluster/designable_paths.txt"
cluster_dir = "/content/cluster"
!./maxcluster64bit -l $designable_file_path "$cluster_dir/all_by_all_lite" -C 2 -in -Rl "$cluster_dir/tm_results.txt" -Tm 0.5 > "$cluster_dir/output.txt"

In [ ]:
output_file = "/content/cluster/output.txt"
designable_dir = "/content/cluster/"
with open(output_file, "r") as f:
    stdout = f.read()
# Extract number of clusters
match = re.search(
    r"INFO\s*:\s*(\d+)\s+Clusters\s+@\s+Threshold\s+(\d+\.\d+)\s+\(\d+\.\d+\)",
    stdout,
)
clusters = int(match.group(1))
cluster_results_path = os.path.join(designable_dir, "cluster_results.txt")
with open(cluster_results_path, "w") as f:
    f.write(stdout)

# Extract cluster centroids
cluster_lines = stdout.split("\n")
centroid_section = False
for line in cluster_lines:
    if "Centroids" in line:
        centroid_section = True
    if centroid_section:
        match = re.search(r"(?<=\s)(\/[^\s]+\.pdb)", line)
        if match is not None:
            centroid_path = match.group(1)
            copy_name = centroid_path.split("/")[-2] + ".pdb"
            shutil.copy(centroid_path, os.path.join(designable_dir, copy_name))

print("Number of decoys in cluster:", clusters)

Number of decoys in cluster: 225

Number of decoys in cluster: 225

## Very_low_noise

In [ ]:
root = "/content/very_low_noise_cleaned"
paths = []
for length in sorted(os.listdir(root)):
    length_path = os.path.join(root, length)
    if not os.path.isdir(length_path):
        continue
    for sample in sorted(os.listdir(length_path)):
        sample_path = os.path.join(length_path, sample)
        if os.path.isdir(sample_path):
            paths.append(sample_path + "/")
df = pd.DataFrame(paths)
df.to_csv("/content/very_low_noise_paths.csv", index=False, header=False)

In [ ]:
!rm -r /content/cluster

In [ ]:
pdb_csv_path="/content/very_low_noise_paths.csv"
pdb_path_list = df[0].tolist()

cluster_dir = os.path.join(Path(pdb_csv_path).parent, "cluster")
os.makedirs(cluster_dir, exist_ok=True)
designable_paths = pdb_path_list
designable_file_path = os.path.join(cluster_dir, "designable_paths.txt")
updated_paths = [os.path.join(path, "sample.pdb") for path in designable_paths]
with open(designable_file_path, "w") as f:
    f.write("\n".join(updated_paths))

print("designable_file_path: ", designable_file_path)
print("cluster_dir: ", cluster_dir)

designable_file_path:  /content/cluster/designable_paths.txt
cluster_dir:  /content/cluster

In [ ]:
designable_file_path = "/content/cluster/designable_paths.txt"
cluster_dir = "/content/cluster"
!./maxcluster64bit -l $designable_file_path "$cluster_dir/all_by_all_lite" -C 2 -in -Rl "$cluster_dir/tm_results.txt" -Tm 0.5 > "$cluster_dir/output.txt"

In [ ]:
output_file = "/content/cluster/output.txt"
designable_dir = "/content/cluster/"
with open(output_file, "r") as f:
    stdout = f.read()
# Extract number of clusters
match = re.search(
    r"INFO\s*:\s*(\d+)\s+Clusters\s+@\s+Threshold\s+(\d+\.\d+)\s+\(\d+\.\d+\)",
    stdout,
)
clusters = int(match.group(1))
cluster_results_path = os.path.join(designable_dir, "cluster_results.txt")
with open(cluster_results_path, "w") as f:
    f.write(stdout)

# Extract cluster centroids
cluster_lines = stdout.split("\n")
centroid_section = False
for line in cluster_lines:
    if "Centroids" in line:
        centroid_section = True
    if centroid_section:
        match = re.search(r"(?<=\s)(\/[^\s]+\.pdb)", line)
        if match is not None:
            centroid_path = match.group(1)
            copy_name = centroid_path.split("/")[-2] + ".pdb"
            shutil.copy(centroid_path, os.path.join(designable_dir, copy_name))

print("Number of decoys in cluster:", clusters)

Number of decoys in cluster: 73

Number of decoys in cluster: 73

## Fast

In [ ]:
root = "/content/fast_cleaned"
paths = []
for length in sorted(os.listdir(root)):
    length_path = os.path.join(root, length)
    if not os.path.isdir(length_path):
        continue
    for sample in sorted(os.listdir(length_path)):
        sample_path = os.path.join(length_path, sample)
        if os.path.isdir(sample_path):
            paths.append(sample_path + "/")
df = pd.DataFrame(paths)
df.to_csv("/content/fast_paths.csv", index=False, header=False)

In [ ]:
!rm -r /content/cluster

In [ ]:
pdb_csv_path="/content/fast_paths.csv"
pdb_path_list = df[0].tolist()

cluster_dir = os.path.join(Path(pdb_csv_path).parent, "cluster")
os.makedirs(cluster_dir, exist_ok=True)
designable_paths = pdb_path_list
designable_file_path = os.path.join(cluster_dir, "designable_paths.txt")
updated_paths = [os.path.join(path, "sample.pdb") for path in designable_paths]
with open(designable_file_path, "w") as f:
    f.write("\n".join(updated_paths))

print("designable_file_path: ", designable_file_path)
print("cluster_dir: ", cluster_dir)

designable_file_path:  /content/cluster/designable_paths.txt
cluster_dir:  /content/cluster

In [ ]:
designable_file_path = "/content/cluster/designable_paths.txt"
cluster_dir = "/content/cluster"
!./maxcluster64bit -l $designable_file_path "$cluster_dir/all_by_all_lite" -C 2 -in -Rl "$cluster_dir/tm_results.txt" -Tm 0.5 > "$cluster_dir/output.txt"

In [ ]:
output_file = "/content/cluster/output.txt"
designable_dir = "/content/cluster/"
with open(output_file, "r") as f:
    stdout = f.read()
# Extract number of clusters
match = re.search(
    r"INFO\s*:\s*(\d+)\s+Clusters\s+@\s+Threshold\s+(\d+\.\d+)\s+\(\d+\.\d+\)",
    stdout,
)
clusters = int(match.group(1))
cluster_results_path = os.path.join(designable_dir, "cluster_results.txt")
with open(cluster_results_path, "w") as f:
    f.write(stdout)

# Extract cluster centroids
cluster_lines = stdout.split("\n")
centroid_section = False
for line in cluster_lines:
    if "Centroids" in line:
        centroid_section = True
    if centroid_section:
        match = re.search(r"(?<=\s)(\/[^\s]+\.pdb)", line)
        if match is not None:
            centroid_path = match.group(1)
            copy_name = centroid_path.split("/")[-2] + ".pdb"
            shutil.copy(centroid_path, os.path.join(designable_dir, copy_name))

print("Number of decoys in cluster:", clusters)

Number of decoys in cluster: 261

Number of decoys in cluster: 261

# Novelty - all sample

In [ ]:
!wget https://mmseqs.com/foldseek/foldseek-linux-avx2.tar.gz
!tar -xzf foldseek-linux-avx2.tar.gz
!cp foldseek/bin/foldseek /usr/local/bin/
!chmod +x /usr/local/bin/foldseek
!mkdir -p /content/foldseek_database
%cd /content/foldseek_database
!foldseek databases PDB pdb tmp

--2026-04-21 01:20:18--  https://mmseqs.com/foldseek/foldseek-linux-avx2.tar.gz
Resolving mmseqs.com (mmseqs.com)... 158.247.200.62
Connecting to mmseqs.com (mmseqs.com)|158.247.200.62|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11689840 (11M) [application/octet-stream]
Saving to: ‘foldseek-linux-avx2.tar.gz’

foldseek-linux-avx2 100%[===================>]  11.15M  5.75MB/s    in 1.9s

2026-04-21 01:20:21 (5.75 MB/s) - ‘foldseek-linux-avx2.tar.gz’ saved [11689840/11689840]

/content/foldseek_database
Create directory tmp
databases PDB pdb tmp

MMseqs Version:              	8dc75c74ad0eddab73cfd905963d13bf74dc012b
Tsv                          	false
Force restart with latest tmp	false
Remove temporary files       	false
Use GPU                      	0
Compressed                   	0
Threads                      	48
Verbosity                    	3

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2219M  100 2219M    0     0  29.5M      0  0:01:15  0:01:15 --:--:-- 31.2M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   121  100   121    0     0    404      0 --:--:-- --:--:-- --:--:--   404
pdb
pdb_ca
pdb_ca.dbtype
pdb_ca.index
pdb_clu
pdb_clu.dbtype
pdb_clu.index
pdb.dbtype
pdb_h
pdb_h.dbtype
pdb_h.index
pdb.index
pdb.lookup
pdb.lookup.tsv
pdb_mapping
pdb.md5sum
pdb_seq.0
pdb_seq.1
pdb_seq_ca.0
pdb_seq_ca.1
pdb_seq_ca.dbtype
pdb_seq_ca.index
pdb_seq.dbtype
pdb_seq_h.0
pdb_seq_h.1
pdb_seq_h.dbtype
pdb_seq_h.index
pdb_seq.index
pdb_seq.lookup
pdb_seq_mapping
pdb_seq.source
pdb_seq_ss.0
pdb_seq_ss.1
pdb_seq_ss.dbtype
pdb_seq_ss.index
pdb_seq_taxonomy
pdb.source
pdb_ss
pdb_ss.dbtype
pdb_ss.index
pdb_taxonomy
mvdb tmp/17761868940115090488/pdb_seq pdb_seq -v 3

Time for processing: 0h 0m 0s 0ms
mvdb tmp/17761868940115090488/pdb pdb -v 3

Time for processing: 0h 0m 0s 0ms
mvdb tmp/17761868940115090488/pdb_seq_ss pdb_seq_ss -v 3

Time for processing: 0h 0m 0s 0ms
mvdb tmp/17761868940115090488/pdb_ss pdb_ss -v 3

Time for processing: 0h 0m 0s 0ms
mvdb tmp/17761868940115090488/pdb_seq_h pdb_seq_h -v 3

Time for processing: 0h 0m 0s 0ms
mvdb tmp/17761868940115090488/pdb_h pdb_h -v 3

Time for processing: 0h 0m 0s 0ms
mvdb tmp/17761868940115090488/pdb_seq_ca pdb_seq_ca -v 3

Time for processing: 0h 0m 0s 0ms
mvdb tmp/17761868940115090488/pdb_ca pdb_ca -v 3

Time for processing: 0h 0m 0s 0ms
mvdb tmp/17761868940115090488/pdb_clu pdb_clu -v 3

Time for processing: 0h 0m 0s 0ms

In [ ]:
from EvalRunner_jupyter import EvalRunner
config_dict = load_config("/content/CS598-GBL/protein/configs/evaluation.yaml")
config_dict["pt_hub_dir"] = "/content/torch_hub"
config_dict["pmpnn_dir"] =  "/content/CS598-GBL/protein/ProteinMPNN"
config_dict["seed"] = 42
config_dict["foldseek_database"] = "/content/foldseek_database/pdb"
config_dict
conf = DictToObject(config_dict)
EvalModel = EvalRunner(conf)

installing libs...
installing openfold...
installing esmfold...
downloading params...

In [ ]:
pdb_path = "/content/CS598-GBL/protein/example_data/length_70/sample_0/sample.pdb"
value = EvalModel.pdbTM(pdb_path)
value

0.88

##Default

In [ ]:
root = "/content/default_cleaned"
rows = []

for length in sorted(os.listdir(root)):
    length_path = os.path.join(root, length)
    if not os.path.isdir(length_path):
        continue
    for sample in sorted(os.listdir(length_path)):
        sample_path = os.path.join(length_path, sample)
        if not os.path.isdir(sample_path):
            continue
        pdb_file = os.path.join(sample_path, "sample.pdb")
        if not os.path.exists(pdb_file):
          continue
        value = EvalModel.pdbTM(pdb_file)
        row = {}
        row["pdbTM"] = float(value)
        row["sample"] = sample
        row["length"] = length
        rows.append(row)
        print(f"{length}/{sample} done")

len_090/sample_0 done
len_090/sample_1 done
len_090/sample_2 done
len_090/sample_3 done
len_090/sample_4 done
len_090/sample_5 done
len_090/sample_6 done
len_090/sample_7 done
len_090/sample_8 done
len_090/sample_9 done
len_091/sample_0 done
len_091/sample_1 done
len_091/sample_2 done
len_091/sample_3 done
len_091/sample_4 done
len_091/sample_5 done
len_091/sample_6 done
len_091/sample_7 done
len_091/sample_8 done
len_091/sample_9 done
len_092/sample_0 done
len_092/sample_1 done
len_092/sample_2 done
len_092/sample_3 done
len_092/sample_4 done
len_092/sample_5 done
len_092/sample_6 done
len_092/sample_7 done
len_092/sample_8 done
len_092/sample_9 done
len_093/sample_0 done
len_093/sample_1 done
len_093/sample_2 done
len_093/sample_3 done
len_093/sample_4 done
len_093/sample_5 done
len_093/sample_6 done
len_093/sample_7 done
len_093/sample_8 done
len_093/sample_9 done
len_094/sample_0 done
len_094/sample_1 done
len_094/sample_2 done
len_094/sample_3 done
len_094/sample_4 done
len_094/sample_5 done
len_094/sample_6 done
len_094/sample_7 done
len_094/sample_8 done
len_094/sample_9 done
len_095/sample_0 done
len_095/sample_1 done
len_095/sample_2 done
len_095/sample_3 done
len_095/sample_4 done
len_095/sample_5 done
len_095/sample_6 done
len_095/sample_7 done
len_095/sample_8 done
len_095/sample_9 done
len_096/sample_0 done
len_096/sample_1 done
len_096/sample_2 done
len_096/sample_3 done
len_096/sample_4 done
len_096/sample_5 done
len_096/sample_6 done
len_096/sample_7 done
len_096/sample_8 done
len_096/sample_9 done
len_097/sample_0 done
len_097/sample_1 done
len_097/sample_2 done
len_097/sample_3 done
len_097/sample_4 done
len_097/sample_5 done
len_097/sample_6 done
len_097/sample_7 done
len_097/sample_8 done
len_097/sample_9 done
len_098/sample_0 done
len_098/sample_1 done
len_098/sample_2 done
len_098/sample_3 done
len_098/sample_4 done
len_098/sample_5 done
len_098/sample_6 done
len_098/sample_7 done
len_098/sample_8 done
len_098/sample_9 done
len_099/sample_0 done
len_099/sample_1 done
len_099/sample_2 done
len_099/sample_3 done
len_099/sample_4 done
len_099/sample_5 done
len_099/sample_6 done
len_099/sample_7 done
len_099/sample_8 done
len_099/sample_9 done
len_100/sample_0 done
len_100/sample_1 done
len_100/sample_2 done
len_100/sample_3 done
len_100/sample_4 done
len_100/sample_5 done
len_100/sample_6 done
len_100/sample_7 done
len_100/sample_8 done
len_100/sample_9 done
len_101/sample_0 done
len_101/sample_1 done
len_101/sample_2 done
len_101/sample_3 done
len_101/sample_4 done
len_101/sample_5 done
len_101/sample_6 done
len_101/sample_7 done
len_101/sample_8 done
len_101/sample_9 done
len_102/sample_0 done
len_102/sample_1 done
len_102/sample_2 done
len_102/sample_3 done
len_102/sample_4 done
len_102/sample_5 done
len_102/sample_6 done
len_102/sample_7 done
len_102/sample_8 done
len_102/sample_9 done
len_103/sample_0 done
len_103/sample_1 done
len_103/sample_2 done
len_103/sample_3 done
len_103/sample_4 done
len_103/sample_5 done
len_103/sample_6 done
len_103/sample_7 done
len_103/sample_8 done
len_103/sample_9 done
len_104/sample_0 done
len_104/sample_1 done
len_104/sample_2 done
len_104/sample_3 done
len_104/sample_4 done
len_104/sample_5 done
len_104/sample_6 done
len_104/sample_7 done
len_104/sample_8 done
len_104/sample_9 done
len_105/sample_0 done
len_105/sample_1 done
len_105/sample_2 done
len_105/sample_3 done
len_105/sample_4 done
len_105/sample_5 done
len_105/sample_6 done
len_105/sample_7 done
len_105/sample_8 done
len_105/sample_9 done
len_106/sample_0 done
len_106/sample_1 done
len_106/sample_2 done
len_106/sample_3 done
len_106/sample_4 done
len_106/sample_5 done
len_106/sample_6 done
len_106/sample_7 done
len_106/sample_8 done
len_106/sample_9 done
len_107/sample_0 done
len_107/sample_1 done
len_107/sample_2 done
len_107/sample_3 done
len_107/sample_4 done
len_107/sample_5 done
len_107/sample_6 done
len_107/sample_7 done
len_107/sample_8 done
len_107/sample_9 done
len_108/sample_0 done
len_108/sample_1 done
len_108/sample_2 done
len_108/sample_3 done
len_108/sample_4 done
len_108/sample_5 done
len_108/sample_6 done
len_108/sample_7 done
len_108/sample_8 done
len_108/sample_9 done
len_109/sample_0 done
len_109/sample_1 done
len_109/sample_2 done
len_109/sample_3 done
len_109/sample_4 done
len_109/sample_5 done
len_109/sample_6 done
len_109/sample_7 done
len_109/sample_8 done
len_109/sample_9 done
len_110/sample_0 done
len_110/sample_1 done
len_110/sample_2 done
len_110/sample_3 done
len_110/sample_4 done
len_110/sample_5 done
len_110/sample_6 done
len_110/sample_7 done
len_110/sample_8 done
len_110/sample_9 done
len_111/sample_0 done
len_111/sample_1 done
len_111/sample_2 done
len_111/sample_3 done
len_111/sample_4 done
len_111/sample_5 done
len_111/sample_6 done
len_111/sample_7 done
len_111/sample_8 done
len_111/sample_9 done
len_112/sample_0 done
len_112/sample_1 done
len_112/sample_2 done
len_112/sample_3 done
len_112/sample_4 done
len_112/sample_5 done
len_112/sample_6 done
len_112/sample_7 done
len_112/sample_8 done
len_112/sample_9 done
len_113/sample_0 done
len_113/sample_1 done
len_113/sample_2 done
len_113/sample_3 done
len_113/sample_4 done
len_113/sample_5 done
len_113/sample_6 done
len_113/sample_7 done
len_113/sample_8 done
len_113/sample_9 done
len_114/sample_0 done
len_114/sample_1 done
len_114/sample_2 done
len_114/sample_3 done
len_114/sample_4 done
len_114/sample_5 done
len_114/sample_6 done
len_114/sample_7 done
len_114/sample_8 done
len_114/sample_9 done
len_115/sample_0 done
len_115/sample_1 done
len_115/sample_2 done
len_115/sample_3 done
len_115/sample_4 done
len_115/sample_5 done
len_115/sample_6 done
len_115/sample_7 done
len_115/sample_8 done
len_115/sample_9 done
len_116/sample_0 done
len_116/sample_1 done
len_116/sample_2 done
len_116/sample_3 done
len_116/sample_4 done
len_116/sample_5 done
len_116/sample_6 done
len_116/sample_7 done
len_116/sample_8 done
len_116/sample_9 done
len_117/sample_0 done
len_117/sample_1 done
len_117/sample_2 done
len_117/sample_3 done
len_117/sample_4 done
len_117/sample_5 done
len_117/sample_6 done
len_117/sample_7 done
len_117/sample_8 done
len_117/sample_9 done
len_118/sample_0 done
len_118/sample_1 done
len_118/sample_2 done
len_118/sample_3 done
len_118/sample_4 done
len_118/sample_5 done
len_118/sample_6 done
len_118/sample_7 done
len_118/sample_8 done
len_118/sample_9 done
len_119/sample_0 done
len_119/sample_1 done
len_119/sample_2 done
len_119/sample_3 done
len_119/sample_4 done
len_119/sample_5 done
len_119/sample_6 done
len_119/sample_7 done
len_119/sample_8 done
len_119/sample_9 done
len_120/sample_0 done
len_120/sample_1 done
len_120/sample_2 done
len_120/sample_3 done
len_120/sample_4 done
len_120/sample_5 done
len_120/sample_6 done
len_120/sample_7 done
len_120/sample_8 done
len_120/sample_9 done
len_121/sample_0 done
len_121/sample_1 done
len_121/sample_2 done
len_121/sample_3 done
len_121/sample_4 done
len_121/sample_5 done
len_121/sample_6 done
len_121/sample_7 done
len_121/sample_8 done
len_121/sample_9 done
len_122/sample_0 done
len_122/sample_1 done
len_122/sample_2 done
len_122/sample_3 done
len_122/sample_4 done
len_122/sample_5 done
len_122/sample_6 done
len_122/sample_7 done
len_122/sample_8 done
len_122/sample_9 done
len_123/sample_0 done
len_123/sample_1 done
len_123/sample_2 done
len_123/sample_3 done
len_123/sample_4 done
len_123/sample_5 done
len_123/sample_6 done
len_123/sample_7 done
len_123/sample_8 done
len_123/sample_9 done
len_124/sample_0 done
len_124/sample_1 done
len_124/sample_2 done
len_124/sample_3 done
len_124/sample_4 done
len_124/sample_5 done
len_124/sample_6 done
len_124/sample_7 done
len_124/sample_8 done
len_124/sample_9 done
len_125/sample_0 done
len_125/sample_1 done
len_125/sample_2 done
len_125/sample_3 done
len_125/sample_4 done
len_125/sample_5 done
len_125/sample_6 done
len_125/sample_7 done
len_125/sample_8 done
len_125/sample_9 done
len_126/sample_0 done
len_126/sample_1 done
len_126/sample_2 done
len_126/sample_3 done
len_126/sample_4 done
len_126/sample_5 done
len_126/sample_6 done
len_126/sample_7 done
len_126/sample_8 done
len_126/sample_9 done
len_127/sample_0 done
len_127/sample_1 done
len_127/sample_2 done
len_127/sample_3 done
len_127/sample_4 done
len_127/sample_5 done
len_127/sample_6 done
len_127/sample_7 done
len_127/sample_8 done
len_127/sample_9 done
len_128/sample_0 done
len_128/sample_1 done
len_128/sample_2 done
len_128/sample_3 done
len_128/sample_4 done
len_128/sample_5 done
len_128/sample_6 done
len_128/sample_7 done
len_128/sample_8 done
len_128/sample_9 done

In [ ]:
df = pd.DataFrame(rows)
df.shape

(390, 3)

In [ ]:
df.to_csv("/content/novelty_default.csv", index=False)
files.download("/content/novelty_default.csv")

## Very_low_noise

In [ ]:
root = "/content/very_low_noise_cleaned"
rows = []

for length in sorted(os.listdir(root)):
    length_path = os.path.join(root, length)
    if not os.path.isdir(length_path):
        continue
    for sample in sorted(os.listdir(length_path)):
        sample_path = os.path.join(length_path, sample)
        if not os.path.isdir(sample_path):
            continue
        pdb_file = os.path.join(sample_path, "sample.pdb")
        if not os.path.exists(pdb_file):
          continue
        value = EvalModel.pdbTM(pdb_file)
        row = {}
        row["pdbTM"] = float(value)
        row["sample"] = sample
        row["length"] = length
        rows.append(row)
        print(f"{length}/{sample} done")

len_090/sample_0 done
len_090/sample_1 done
len_090/sample_2 done
len_090/sample_3 done
len_090/sample_4 done
len_090/sample_5 done
len_090/sample_6 done
len_090/sample_7 done
len_090/sample_8 done
len_090/sample_9 done
len_091/sample_0 done
len_091/sample_1 done
len_091/sample_2 done
len_091/sample_3 done
len_091/sample_4 done
len_091/sample_5 done
len_091/sample_6 done
len_091/sample_7 done
len_091/sample_8 done
len_091/sample_9 done
len_092/sample_0 done
len_092/sample_1 done
len_092/sample_2 done
len_092/sample_3 done
len_092/sample_4 done
len_092/sample_5 done
len_092/sample_6 done
len_092/sample_7 done
len_092/sample_8 done
len_092/sample_9 done
len_093/sample_0 done
len_093/sample_1 done
len_093/sample_2 done
len_093/sample_3 done
len_093/sample_4 done
len_093/sample_5 done
len_093/sample_6 done
len_093/sample_7 done
len_093/sample_8 done
len_093/sample_9 done
len_094/sample_0 done
len_094/sample_1 done
len_094/sample_2 done
len_094/sample_3 done
len_094/sample_4 done
len_094/sample_5 done
len_094/sample_6 done
len_094/sample_7 done
len_094/sample_8 done
len_094/sample_9 done
len_095/sample_0 done
len_095/sample_1 done
len_095/sample_2 done
len_095/sample_3 done
len_095/sample_4 done
len_095/sample_5 done
len_095/sample_6 done
len_095/sample_7 done
len_095/sample_8 done
len_095/sample_9 done
len_096/sample_0 done
len_096/sample_1 done
len_096/sample_2 done
len_096/sample_3 done
len_096/sample_4 done
len_096/sample_5 done
len_096/sample_6 done
len_096/sample_7 done
len_096/sample_8 done
len_096/sample_9 done
len_097/sample_0 done
len_097/sample_1 done
len_097/sample_2 done
len_097/sample_3 done
len_097/sample_4 done
len_097/sample_5 done
len_097/sample_6 done
len_097/sample_7 done
len_097/sample_8 done
len_097/sample_9 done
len_098/sample_0 done
len_098/sample_1 done
len_098/sample_2 done
len_098/sample_3 done
len_098/sample_4 done
len_098/sample_5 done
len_098/sample_6 done
len_098/sample_7 done
len_098/sample_8 done
len_098/sample_9 done
len_099/sample_0 done
len_099/sample_1 done
len_099/sample_2 done
len_099/sample_3 done
len_099/sample_4 done
len_099/sample_5 done
len_099/sample_6 done
len_099/sample_7 done
len_099/sample_8 done
len_099/sample_9 done
len_100/sample_0 done
len_100/sample_1 done
len_100/sample_2 done
len_100/sample_3 done
len_100/sample_4 done
len_100/sample_5 done
len_100/sample_6 done
len_100/sample_7 done
len_100/sample_8 done
len_100/sample_9 done
len_101/sample_0 done
len_101/sample_1 done
len_101/sample_2 done
len_101/sample_3 done
len_101/sample_4 done
len_101/sample_5 done
len_101/sample_6 done
len_101/sample_7 done
len_101/sample_8 done
len_101/sample_9 done
len_102/sample_0 done
len_102/sample_1 done
len_102/sample_2 done
len_102/sample_3 done
len_102/sample_4 done
len_102/sample_5 done
len_102/sample_6 done
len_102/sample_7 done
len_102/sample_8 done
len_102/sample_9 done
len_103/sample_0 done
len_103/sample_1 done
len_103/sample_2 done
len_103/sample_3 done
len_103/sample_4 done
len_103/sample_5 done
len_103/sample_6 done
len_103/sample_7 done
len_103/sample_8 done
len_103/sample_9 done
len_104/sample_0 done
len_104/sample_1 done
len_104/sample_2 done
len_104/sample_3 done
len_104/sample_4 done
len_104/sample_5 done
len_104/sample_6 done
len_104/sample_7 done
len_104/sample_8 done
len_104/sample_9 done
len_105/sample_0 done
len_105/sample_1 done
len_105/sample_2 done
len_105/sample_3 done
len_105/sample_4 done
len_105/sample_5 done
len_105/sample_6 done
len_105/sample_7 done
len_105/sample_8 done
len_105/sample_9 done
len_106/sample_0 done
len_106/sample_1 done
len_106/sample_2 done
len_106/sample_3 done
len_106/sample_4 done
len_106/sample_5 done
len_106/sample_6 done
len_106/sample_7 done
len_106/sample_8 done
len_106/sample_9 done
len_107/sample_0 done
len_107/sample_1 done
len_107/sample_2 done
len_107/sample_3 done
len_107/sample_4 done
len_107/sample_5 done
len_107/sample_6 done
len_107/sample_7 done
len_107/sample_8 done
len_107/sample_9 done
len_108/sample_0 done
len_108/sample_1 done
len_108/sample_2 done
len_108/sample_3 done
len_108/sample_4 done
len_108/sample_5 done
len_108/sample_6 done
len_108/sample_7 done
len_108/sample_8 done
len_108/sample_9 done
len_109/sample_0 done
len_109/sample_1 done
len_109/sample_2 done
len_109/sample_3 done
len_109/sample_4 done
len_109/sample_5 done
len_109/sample_6 done
len_109/sample_7 done
len_109/sample_8 done
len_109/sample_9 done
len_110/sample_0 done
len_110/sample_1 done
len_110/sample_2 done
len_110/sample_3 done
len_110/sample_4 done
len_110/sample_5 done
len_110/sample_6 done
len_110/sample_7 done
len_110/sample_8 done
len_110/sample_9 done
len_111/sample_0 done
len_111/sample_1 done
len_111/sample_2 done
len_111/sample_3 done
len_111/sample_4 done
len_111/sample_5 done
len_111/sample_6 done
len_111/sample_7 done
len_111/sample_8 done
len_111/sample_9 done
len_112/sample_0 done
len_112/sample_1 done
len_112/sample_2 done
len_112/sample_3 done
len_112/sample_4 done
len_112/sample_5 done
len_112/sample_6 done
len_112/sample_7 done
len_112/sample_8 done
len_112/sample_9 done
len_113/sample_0 done
len_113/sample_1 done
len_113/sample_2 done
len_113/sample_3 done
len_113/sample_4 done
len_113/sample_5 done
len_113/sample_6 done
len_113/sample_7 done
len_113/sample_8 done
len_113/sample_9 done
len_114/sample_0 done
len_114/sample_1 done
len_114/sample_2 done
len_114/sample_3 done
len_114/sample_4 done
len_114/sample_5 done
len_114/sample_6 done
len_114/sample_7 done
len_114/sample_8 done
len_114/sample_9 done
len_115/sample_0 done
len_115/sample_1 done
len_115/sample_2 done
len_115/sample_3 done
len_115/sample_4 done
len_115/sample_5 done
len_115/sample_6 done
len_115/sample_7 done
len_115/sample_8 done
len_115/sample_9 done
len_116/sample_0 done
len_116/sample_1 done
len_116/sample_2 done
len_116/sample_3 done
len_116/sample_4 done
len_116/sample_5 done
len_116/sample_6 done
len_116/sample_7 done
len_116/sample_8 done
len_116/sample_9 done
len_117/sample_0 done
len_117/sample_1 done
len_117/sample_2 done
len_117/sample_3 done
len_117/sample_4 done
len_117/sample_5 done
len_117/sample_6 done
len_117/sample_7 done
len_117/sample_8 done
len_117/sample_9 done
len_118/sample_0 done
len_118/sample_1 done
len_118/sample_2 done
len_118/sample_3 done
len_118/sample_4 done
len_118/sample_5 done
len_118/sample_6 done
len_118/sample_7 done
len_118/sample_8 done
len_118/sample_9 done
len_119/sample_0 done
len_119/sample_1 done
len_119/sample_2 done
len_119/sample_3 done
len_119/sample_4 done
len_119/sample_5 done
len_119/sample_6 done
len_119/sample_7 done
len_119/sample_8 done
len_119/sample_9 done
len_120/sample_0 done
len_120/sample_1 done
len_120/sample_2 done
len_120/sample_3 done
len_120/sample_4 done
len_120/sample_5 done
len_120/sample_6 done
len_120/sample_7 done
len_120/sample_8 done
len_120/sample_9 done
len_121/sample_0 done
len_121/sample_1 done
len_121/sample_2 done
len_121/sample_3 done
len_121/sample_4 done
len_121/sample_5 done
len_121/sample_6 done
len_121/sample_7 done
len_121/sample_8 done
len_121/sample_9 done
len_122/sample_0 done
len_122/sample_1 done
len_122/sample_2 done
len_122/sample_3 done
len_122/sample_4 done
len_122/sample_5 done
len_122/sample_6 done
len_122/sample_7 done
len_122/sample_8 done
len_122/sample_9 done
len_123/sample_0 done
len_123/sample_1 done
len_123/sample_2 done
len_123/sample_3 done
len_123/sample_4 done
len_123/sample_5 done
len_123/sample_6 done
len_123/sample_7 done
len_123/sample_8 done
len_123/sample_9 done
len_124/sample_0 done
len_124/sample_1 done
len_124/sample_2 done
len_124/sample_3 done
len_124/sample_4 done
len_124/sample_5 done
len_124/sample_6 done
len_124/sample_7 done
len_124/sample_8 done
len_124/sample_9 done
len_125/sample_0 done
len_125/sample_1 done
len_125/sample_2 done
len_125/sample_3 done
len_125/sample_4 done
len_125/sample_5 done
len_125/sample_6 done
len_125/sample_7 done
len_125/sample_8 done
len_125/sample_9 done
len_126/sample_0 done
len_126/sample_1 done
len_126/sample_2 done
len_126/sample_3 done
len_126/sample_4 done
len_126/sample_5 done
len_126/sample_6 done
len_126/sample_7 done
len_126/sample_8 done
len_126/sample_9 done
len_127/sample_0 done
len_127/sample_1 done
len_127/sample_2 done
len_127/sample_3 done
len_127/sample_4 done
len_127/sample_5 done
len_127/sample_6 done
len_127/sample_7 done
len_127/sample_8 done
len_127/sample_9 done
len_128/sample_0 done
len_128/sample_1 done
len_128/sample_2 done
len_128/sample_3 done
len_128/sample_4 done
len_128/sample_5 done
len_128/sample_6 done
len_128/sample_7 done
len_128/sample_8 done
len_128/sample_9 done

In [ ]:
df = pd.DataFrame(rows)
df.to_csv("/content/novelty_very_low_noise.csv", index=False)
files.download("/content/novelty_very_low_noise.csv")

## Fast

In [ ]:
root = "/content/fast_cleaned"
rows = []

for length in sorted(os.listdir(root)):
    length_path = os.path.join(root, length)
    if not os.path.isdir(length_path):
        continue
    for sample in sorted(os.listdir(length_path)):
        sample_path = os.path.join(length_path, sample)
        if not os.path.isdir(sample_path):
            continue
        pdb_file = os.path.join(sample_path, "sample.pdb")
        if not os.path.exists(pdb_file):
          continue
        value = EvalModel.pdbTM(pdb_file)
        row = {}
        row["pdbTM"] = float(value)
        row["sample"] = sample
        row["length"] = length
        rows.append(row)
        print(f"{length}/{sample} done")

len_090/sample_0 done
len_090/sample_1 done
len_090/sample_2 done
len_090/sample_3 done
len_090/sample_4 done
len_090/sample_5 done
len_090/sample_6 done
len_090/sample_7 done
len_090/sample_8 done
len_090/sample_9 done
len_091/sample_0 done
len_091/sample_1 done
len_091/sample_2 done
len_091/sample_3 done
len_091/sample_4 done
len_091/sample_5 done
len_091/sample_6 done
len_091/sample_7 done
len_091/sample_8 done
len_091/sample_9 done
len_092/sample_0 done
len_092/sample_1 done
len_092/sample_2 done
len_092/sample_3 done
len_092/sample_4 done
len_092/sample_5 done
len_092/sample_6 done
len_092/sample_7 done
len_092/sample_8 done
len_092/sample_9 done
len_093/sample_0 done
len_093/sample_1 done
len_093/sample_2 done
len_093/sample_3 done
len_093/sample_4 done
len_093/sample_5 done
len_093/sample_6 done
len_093/sample_7 done
len_093/sample_8 done
len_093/sample_9 done
len_094/sample_0 done
len_094/sample_1 done
len_094/sample_2 done
len_094/sample_3 done
len_094/sample_4 done
len_094/sample_5 done
len_094/sample_6 done
len_094/sample_7 done
len_094/sample_8 done
len_094/sample_9 done
len_095/sample_0 done
len_095/sample_1 done
len_095/sample_2 done
len_095/sample_3 done
len_095/sample_4 done
len_095/sample_5 done
len_095/sample_6 done
len_095/sample_7 done
len_095/sample_8 done
len_095/sample_9 done
len_096/sample_0 done
len_096/sample_1 done
len_096/sample_2 done
len_096/sample_3 done
len_096/sample_4 done
len_096/sample_5 done
len_096/sample_6 done
len_096/sample_7 done
len_096/sample_8 done
len_096/sample_9 done
len_097/sample_0 done
len_097/sample_1 done
len_097/sample_2 done
len_097/sample_3 done
len_097/sample_4 done
len_097/sample_5 done
len_097/sample_6 done
len_097/sample_7 done
len_097/sample_8 done
len_097/sample_9 done
len_098/sample_0 done
len_098/sample_1 done
len_098/sample_2 done
len_098/sample_3 done
len_098/sample_4 done
len_098/sample_5 done
len_098/sample_6 done
len_098/sample_7 done
len_098/sample_8 done
len_098/sample_9 done
len_099/sample_0 done
len_099/sample_1 done
len_099/sample_2 done
len_099/sample_3 done
len_099/sample_4 done
len_099/sample_5 done
len_099/sample_6 done
len_099/sample_7 done
len_099/sample_8 done
len_099/sample_9 done
len_100/sample_0 done
len_100/sample_1 done
len_100/sample_2 done
len_100/sample_3 done
len_100/sample_4 done
len_100/sample_5 done
len_100/sample_6 done
len_100/sample_7 done
len_100/sample_8 done
len_100/sample_9 done
len_101/sample_0 done
len_101/sample_1 done
len_101/sample_2 done
len_101/sample_3 done
len_101/sample_4 done
len_101/sample_5 done
len_101/sample_6 done
len_101/sample_7 done
len_101/sample_8 done
len_101/sample_9 done
len_102/sample_0 done
len_102/sample_1 done
len_102/sample_2 done
len_102/sample_3 done
len_102/sample_4 done
len_102/sample_5 done
len_102/sample_6 done
len_102/sample_7 done
len_102/sample_8 done
len_102/sample_9 done
len_103/sample_0 done
len_103/sample_1 done
len_103/sample_2 done
len_103/sample_3 done
len_103/sample_4 done
len_103/sample_5 done
len_103/sample_6 done
len_103/sample_7 done
len_103/sample_8 done
len_103/sample_9 done
len_104/sample_0 done
len_104/sample_1 done
len_104/sample_2 done
len_104/sample_3 done
len_104/sample_4 done
len_104/sample_5 done
len_104/sample_6 done
len_104/sample_7 done
len_104/sample_8 done
len_104/sample_9 done
len_105/sample_0 done
len_105/sample_1 done
len_105/sample_2 done
len_105/sample_3 done
len_105/sample_4 done
len_105/sample_5 done
len_105/sample_6 done
len_105/sample_7 done
len_105/sample_8 done
len_105/sample_9 done
len_106/sample_0 done
len_106/sample_1 done
len_106/sample_2 done
len_106/sample_3 done
len_106/sample_4 done
len_106/sample_5 done
len_106/sample_6 done
len_106/sample_7 done
len_106/sample_8 done
len_106/sample_9 done
len_107/sample_0 done
len_107/sample_1 done
len_107/sample_2 done
len_107/sample_3 done
len_107/sample_4 done
len_107/sample_5 done
len_107/sample_6 done
len_107/sample_7 done
len_107/sample_8 done
len_107/sample_9 done
len_108/sample_0 done
len_108/sample_1 done
len_108/sample_2 done
len_108/sample_3 done
len_108/sample_4 done
len_108/sample_5 done
len_108/sample_6 done
len_108/sample_7 done
len_108/sample_8 done
len_108/sample_9 done
len_109/sample_0 done
len_109/sample_1 done
len_109/sample_2 done
len_109/sample_3 done
len_109/sample_4 done
len_109/sample_5 done
len_109/sample_6 done
len_109/sample_7 done
len_109/sample_8 done
len_109/sample_9 done
len_110/sample_0 done
len_110/sample_1 done
len_110/sample_2 done
len_110/sample_3 done
len_110/sample_4 done
len_110/sample_5 done
len_110/sample_6 done
len_110/sample_7 done
len_110/sample_8 done
len_110/sample_9 done
len_111/sample_0 done
len_111/sample_1 done
len_111/sample_2 done
len_111/sample_3 done
len_111/sample_4 done
len_111/sample_5 done
len_111/sample_6 done
len_111/sample_7 done
len_111/sample_8 done
len_111/sample_9 done
len_112/sample_0 done
len_112/sample_1 done
len_112/sample_2 done
len_112/sample_3 done
len_112/sample_4 done
len_112/sample_5 done
len_112/sample_6 done
len_112/sample_7 done
len_112/sample_8 done
len_112/sample_9 done
len_113/sample_0 done
len_113/sample_1 done
len_113/sample_2 done
len_113/sample_3 done
len_113/sample_4 done
len_113/sample_5 done
len_113/sample_6 done
len_113/sample_7 done
len_113/sample_8 done
len_113/sample_9 done
len_114/sample_0 done
len_114/sample_1 done
len_114/sample_2 done
len_114/sample_3 done
len_114/sample_4 done
len_114/sample_5 done
len_114/sample_6 done
len_114/sample_7 done
len_114/sample_8 done
len_114/sample_9 done
len_115/sample_0 done
len_115/sample_1 done
len_115/sample_2 done
len_115/sample_3 done
len_115/sample_4 done
len_115/sample_5 done
len_115/sample_6 done
len_115/sample_7 done
len_115/sample_8 done
len_115/sample_9 done
len_116/sample_0 done
len_116/sample_1 done
len_116/sample_2 done
len_116/sample_3 done
len_116/sample_4 done
len_116/sample_5 done
len_116/sample_6 done
len_116/sample_7 done
len_116/sample_8 done
len_116/sample_9 done
len_117/sample_0 done
len_117/sample_1 done
len_117/sample_2 done
len_117/sample_3 done
len_117/sample_4 done
len_117/sample_5 done
len_117/sample_6 done
len_117/sample_7 done
len_117/sample_8 done
len_117/sample_9 done
len_118/sample_0 done
len_118/sample_1 done
len_118/sample_2 done
len_118/sample_3 done
len_118/sample_4 done
len_118/sample_5 done
len_118/sample_6 done
len_118/sample_7 done
len_118/sample_8 done
len_118/sample_9 done
len_119/sample_0 done
len_119/sample_1 done
len_119/sample_2 done
len_119/sample_3 done
len_119/sample_4 done
len_119/sample_5 done
len_119/sample_6 done
len_119/sample_7 done
len_119/sample_8 done
len_119/sample_9 done
len_120/sample_0 done
len_120/sample_1 done
len_120/sample_2 done
len_120/sample_3 done
len_120/sample_4 done
len_120/sample_5 done
len_120/sample_6 done
len_120/sample_7 done
len_120/sample_8 done
len_120/sample_9 done
len_121/sample_0 done
len_121/sample_1 done
len_121/sample_2 done
len_121/sample_3 done
len_121/sample_4 done
len_121/sample_5 done
len_121/sample_6 done
len_121/sample_7 done
len_121/sample_8 done
len_121/sample_9 done
len_122/sample_0 done
len_122/sample_1 done
len_122/sample_2 done
len_122/sample_3 done
len_122/sample_4 done
len_122/sample_5 done
len_122/sample_6 done
len_122/sample_7 done
len_122/sample_8 done
len_122/sample_9 done
len_123/sample_0 done
len_123/sample_1 done
len_123/sample_2 done
len_123/sample_3 done
len_123/sample_4 done
len_123/sample_5 done
len_123/sample_6 done
len_123/sample_7 done
len_123/sample_8 done
len_123/sample_9 done
len_124/sample_0 done
len_124/sample_1 done
len_124/sample_2 done
len_124/sample_3 done
len_124/sample_4 done
len_124/sample_5 done
len_124/sample_6 done
len_124/sample_7 done
len_124/sample_8 done
len_124/sample_9 done
len_125/sample_0 done
len_125/sample_1 done
len_125/sample_2 done
len_125/sample_3 done
len_125/sample_4 done
len_125/sample_5 done
len_125/sample_6 done
len_125/sample_7 done
len_125/sample_8 done
len_125/sample_9 done
len_126/sample_0 done
len_126/sample_1 done
len_126/sample_2 done
len_126/sample_3 done
len_126/sample_4 done
len_126/sample_5 done
len_126/sample_6 done
len_126/sample_7 done
len_126/sample_8 done
len_126/sample_9 done
len_127/sample_0 done
len_127/sample_1 done
len_127/sample_2 done
len_127/sample_3 done
len_127/sample_4 done
len_127/sample_5 done
len_127/sample_6 done
len_127/sample_7 done
len_127/sample_8 done
len_127/sample_9 done
len_128/sample_0 done
len_128/sample_1 done
len_128/sample_2 done
len_128/sample_3 done
len_128/sample_4 done
len_128/sample_5 done
len_128/sample_6 done
len_128/sample_7 done
len_128/sample_8 done
len_128/sample_9 done

In [ ]:
df = pd.DataFrame(rows)
df.to_csv("/content/fast.csv", index=False)
files.download("/content/fast.csv")

# Designability&designable backbones

## Default

In [ ]:
df = pd.read_csv("/content/rmsd_default_results.csv")

In [ ]:
design_df = (
    df.groupby(["length", "sample"], as_index=False)["bb_rmsd"].min().rename(columns={"bb_rmsd": "min_scRMSD"})
)
design_df.head()

    length    sample  min_scRMSD
0  len_090  sample_0    0.848177
1  len_090  sample_1    1.133535
2  len_090  sample_2    7.427496
3  len_090  sample_3    0.467946
4  len_090  sample_4    0.536097

In [ ]:
design_df.shape

(390, 3)

In [ ]:
design_df["designable"] = design_df["min_scRMSD"] < 2.0
design_df.head()

    length    sample  min_scRMSD  designable
0  len_090  sample_0    0.848177        True
1  len_090  sample_1    1.133535        True
2  len_090  sample_2    7.427496       False
3  len_090  sample_3    0.467946        True
4  len_090  sample_4    0.536097        True

In [ ]:
num_designable = design_df["designable"].sum()
num_total = len(design_df)
designability = num_designable / num_total
print("Designable:", num_designable)
print("Total:", num_total)
print("Designability:", designability)

Designable: 370
Total: 390
Designability: 0.9487179487179487

In [ ]:
designable_df = design_df[design_df["designable"]].copy()
designable_df.shape

(370, 4)

In [ ]:
designable_df["pdb_path"] = ("/content/default_cleaned/" + designable_df["length"] + "/" + designable_df["sample"]
                             + "/sample.pdb")
designable_df.head()
designable_df.to_csv("/content/default_designable.csv", index=False)
files.download("/content/default_designable.csv")

In [ ]:
dst_dir = "/content/default_designable_samples"
os.makedirs(dst_dir, exist_ok=True)
for _, row in designable_df.iterrows():
    src = row["pdb_path"]
    if not os.path.exists(src):
        continue
    length = row["length"]
    sample = row["sample"]
    dst_name = f"{length}_{sample}.pdb"
    dst = os.path.join(dst_dir, dst_name)
    shutil.copy(src, dst)

In [ ]:
len(os.listdir("/content/default_designable_samples"))

370

In [ ]:
!zip -r /content/default_designable_samples.zip /content/default_designable_samples
files.download("/content/default_designable_samples.zip")

  adding: content/default_designable_samples/ (stored 0%)
  adding: content/default_designable_samples/len_109_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_127_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_101_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_111_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_103_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_100_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_127_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_104_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_116_sample_3.pdb (deflated 76%)
  adding: content/default_designable_samples/len_093_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_116_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_092_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_104_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_121_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_117_sample_5.pdb (deflated 76%)
  adding: content/default_designable_samples/len_106_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_123_sample_8.pdb (deflated 77%)
  adding: content/default_designable_samples/len_115_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_105_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_102_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_109_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_094_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_124_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_111_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_098_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_119_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_108_sample_8.pdb (deflated 77%)
  adding: content/default_designable_samples/len_100_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_117_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_108_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_093_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_113_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_094_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_105_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_118_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_119_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_103_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_107_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_109_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_090_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_107_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_115_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_111_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_096_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_106_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_121_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_125_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_116_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_108_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_115_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_109_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_115_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_105_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_119_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_124_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_094_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_117_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_106_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_093_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_091_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_105_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_090_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_120_sample_8.pdb (deflated 77%)
  adding: content/default_designable_samples/len_094_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_120_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_098_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_098_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_117_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_120_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_125_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_108_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_107_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_128_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_105_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_095_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_101_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_097_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_099_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_097_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_125_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_118_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_096_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_121_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_113_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_106_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_097_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_118_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_107_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_127_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_099_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_099_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_102_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_093_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_124_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_128_sample_8.pdb (deflated 77%)
  adding: content/default_designable_samples/len_095_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_105_sample_8.pdb (deflated 76%)
  adding: content/default_designable_samples/len_112_sample_8.pdb (deflated 77%)
  adding: content/default_designable_samples/len_120_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_096_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_112_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_102_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_091_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_099_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_112_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_126_sample_8.pdb (deflated 77%)
  adding: content/default_designable_samples/len_097_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_127_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_099_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_091_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_111_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_108_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_109_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_111_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_101_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_091_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_092_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_127_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_107_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_106_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_122_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_101_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_098_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_122_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_093_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_121_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_113_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_114_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_118_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_110_sample_8.pdb (deflated 77%)
  adding: content/default_designable_samples/len_102_sample_8.pdb (deflated 77%)
  adding: content/default_designable_samples/len_121_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_127_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_118_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_125_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_102_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_113_sample_8.pdb (deflated 77%)
  adding: content/default_designable_samples/len_092_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_123_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_112_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_105_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_098_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_114_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_093_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_121_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_124_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_093_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_112_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_117_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_121_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_101_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_112_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_100_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_091_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_110_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_125_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_095_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_123_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_122_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_125_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_114_sample_8.pdb (deflated 77%)
  adding: content/default_designable_samples/len_111_sample_8.pdb (deflated 77%)
  adding: content/default_designable_samples/len_097_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_112_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_098_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_124_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_113_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_103_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_110_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_127_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_103_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_105_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_095_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_095_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_114_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_108_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_115_sample_8.pdb (deflated 77%)
  adding: content/default_designable_samples/len_126_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_099_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_128_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_092_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_102_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_112_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_108_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_103_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_128_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_094_sample_8.pdb (deflated 77%)
  adding: content/default_designable_samples/len_096_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_092_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_122_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_098_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_119_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_121_sample_8.pdb (deflated 77%)
  adding: content/default_designable_samples/len_098_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_125_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_110_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_123_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_097_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_111_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_116_sample_6.pdb (deflated 77%)
  adding: content/default_designable_samples/len_102_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_099_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_118_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_114_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_092_sample_8.pdb (deflated 77%)
  adding: content/default_designable_samples/len_107_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_115_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_093_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_092_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_118_sample_8.pdb (deflated 77%)
  adding: content/default_designable_samples/len_123_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_109_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_117_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_123_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_103_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_126_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_090_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_114_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_119_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_092_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_119_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_111_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_095_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_102_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_120_sample_4.pdb (deflated 77%)
  adding: content/default_designable_samples/len_104_sample_0.pdb (deflated 76%)
  adding: content/default_designable_samples/len_109_sample_8.pdb (deflated 77%)
  adding: content/default_designable_samples/len_117_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_109_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_122_sample_9.pdb (deflated 76%)
  adding: content/default_designable_samples/len_127_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_108_sample_2.pdb (deflated 77%)
  adding: content/default_designable_samples/len_120_sample_9.pdb (deflated 77%)
  adding: content/default_designable_samples/len_122_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_100_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_112_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_107_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_116_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_100_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_092_sample_1.pdb (deflated 77%)
  adding: content/default_designable_samples/len_095_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_126_sample_5.pdb (deflated 77%)
  adding: content/default_designable_samples/len_124_sample_3.pdb (deflated 77%)
  adding: content/default_designable_samples/len_112_sample_0.pdb (deflated 77%)
  adding: content/default_designable_samples/len_109_sample_7.pdb (deflated 77%)
  adding: content/default_designable_samples/len_118_sample_0.pdb (deflated 77%)

##Very low noise

In [ ]:
df = pd.read_csv("/content/rmsd_very_low_noise_results.csv")
design_df = (
    df.groupby(["length", "sample"], as_index=False)["bb_rmsd"].min().rename(columns={"bb_rmsd": "min_scRMSD"})
)
design_df["designable"] = design_df["min_scRMSD"] < 2.0
num_designable = design_df["designable"].sum()
num_total = len(design_df)
designability = num_designable / num_total
print("Designable:", num_designable)
print("Total:", num_total)
print("Designability:", designability)

Designable: 388
Total: 390
Designability: 0.9948717948717949

In [ ]:
designable_df = design_df[design_df["designable"]].copy()
designable_df.shape

(388, 4)

In [ ]:
designable_df["pdb_path"] = ("/content/very_low_noise_cleaned/" + designable_df["length"] + "/" + designable_df["sample"]
                             + "/sample.pdb")
designable_df.head()
designable_df.to_csv("/content/very_low_noise_designable.csv", index=False)
files.download("/content/very_low_noise_designable.csv")

In [ ]:
dst_dir = "/content/very_low_noise_designable_samples"
os.makedirs(dst_dir, exist_ok=True)
for _, row in designable_df.iterrows():
    src = row["pdb_path"]
    if not os.path.exists(src):
        continue
    length = row["length"]
    sample = row["sample"]
    dst_name = f"{length}_{sample}.pdb"
    dst = os.path.join(dst_dir, dst_name)
    shutil.copy(src, dst)

In [ ]:
len(os.listdir("/content/very_low_noise_designable_samples"))

388

In [ ]:
!zip -rq /content/very_low_noise_designable_samples.zip /content/very_low_noise_designable_samples
files.download("/content/very_low_noise_designable_samples.zip")

## Fast

In [ ]:
df = pd.read_csv("/content/rmsd_fast_results.csv")
design_df = (
    df.groupby(["length", "sample"], as_index=False)["bb_rmsd"].min().rename(columns={"bb_rmsd": "min_scRMSD"})
)
design_df["designable"] = design_df["min_scRMSD"] < 2.0
num_designable = design_df["designable"].sum()
num_total = len(design_df)
designability = num_designable / num_total
print("Designable:", num_designable)
print("Total:", num_total)
print("Designability:", designability)

Designable: 341
Total: 390
Designability: 0.8743589743589744

In [ ]:
designable_df = design_df[design_df["designable"]].copy()
designable_df.shape

(341, 4)

In [ ]:
designable_df["pdb_path"] = ("/content/fast_cleaned/" + designable_df["length"] + "/" + designable_df["sample"]
                             + "/sample.pdb")
designable_df.head()
designable_df.to_csv("/content/fast_designable.csv", index=False)
files.download("/content/fast_designable.csv")

In [ ]:
dst_dir = "/content/fast_designable_samples"
os.makedirs(dst_dir, exist_ok=True)
for _, row in designable_df.iterrows():
    src = row["pdb_path"]
    if not os.path.exists(src):
        continue
    length = row["length"]
    sample = row["sample"]
    dst_name = f"{length}_{sample}.pdb"
    dst = os.path.join(dst_dir, dst_name)
    shutil.copy(src, dst)

In [ ]:
len(os.listdir("/content/fast_designable_samples"))

341

In [ ]:
!zip -rq /content/fast_designable_samples.zip /content/fast_designable_samples
files.download("/content/fast_designable_samples.zip")

#Clustering using foldseek

## Default

In [ ]:
!mkdir -p /content/default/tmp
!mkdir -p /content/default/res

In [ ]:
!foldseek easy-cluster /content/default_designable_samples /content/default/res /content/default/tmp --alignment-type 1 --tmscore-threshold 0.5 --tmscore-threshold-mode 0

/content/default/res exists and will be overwritten
easy-cluster /content/default_designable_samples /content/default/res /content/default/tmp --alignment-type 1 --tmscore-threshold 0.5 --tmscore-threshold-mode 0

MMseqs Version:                     	8dc75c74ad0eddab73cfd905963d13bf74dc012b
Substitution matrix                 	aa:3di.out,nucl:3di.out
Seed substitution matrix            	aa:3di.out,nucl:3di.out
Sensitivity                         	4
k-mer length                        	0
Target search mode                  	0
k-score                             	seq:2147483647,prof:2147483647
Max sequence length                 	65535
Max results per query               	300
Split database                      	0
Split mode                          	2
Split memory limit                  	0
Coverage threshold                  	0
Coverage mode                       	0
Compositional bias                  	1
Compositional bias scale            	1
Diagonal scoring                    	true
Exact k-mer matching                	0
Mask residues                       	0
Mask residues probability           	0.999995
Mask lower case residues            	1
Mask lower letter repeating N times 	6
Minimum diagonal score              	30
Selected taxa
Spaced k-mers                       	1
Preload mode                        	0
Spaced k-mer pattern
Local temporary path
Threads                             	48
Compressed                          	0
Verbosity                           	3
TMscore threshold                   	0.5
TMscore threshold mode              	0
LDDT threshold                      	0
Sort by structure bit score         	1
Alignment type                      	1
Exact TMscore                       	0
Add backtrace                       	false
Alignment mode                      	0
Alignment mode                      	0
E-value threshold                   	10
Seq. id. threshold                  	0
Min alignment length                	0
Seq. id. mode                       	0
Alternative alignments              	0
Max reject                          	2147483647
Max accept                          	2147483647
Gap open cost                       	aa:10,nucl:10
Gap extension cost                  	aa:1,nucl:1
TMalign hit order                   	0
TMalign fast                        	1
Cluster mode                        	0
Max connected component depth       	1000
Similarity type                     	2
Weight file name
Cluster Weight threshold            	0.9
Set mode                            	false
Single step clustering              	false
Cascaded clustering steps           	3
Cluster reassign                    	false
Remove temporary files              	true
Force restart with latest tmp       	false
MPI runner
k-mers per sequence                 	21
Scale k-mers per sequence           	aa:0.000,nucl:0.200
Adjust k-mer length                 	false
Shift hash                          	67
Include only extendable             	false
Skip repeating k-mers               	false
Rescore mode                        	0
Remove hits by seq. id. and coverage	false
Sort results                        	0
Use GPU                             	0
Path to ProstT5
Chain name mode                     	0
Model name mode                     	0
Createdb extraction mode            	0
Interface distance threshold        	10
Write mapping file                  	0
Write Foldcomp                      	0
Mask b-factor threshold             	0
Coord store mode                    	2
Write lookup file                   	1
Input format                        	0
Input compression format            	0
File Inclusion Regex                	.*
File Exclusion Regex                	^$

createdb /content/default_designable_samples /content/default/tmp/15576934524713146554/input --gpu 0 --chain-name-mode 0 --model-name-mode 0 --db-extraction-mode 0 --distance-threshold 10 --write-mapping 0 --write-foldcomp 0 --mask-bfactor-threshold 0 --coord-store-mode 2 --write-lookup 1 --input-format 0 --input-compression-format 0 --file-include '.*' --file-exclude '^$' --threads 48 -v 3

Output file: /content/default/tmp/15576934524713146554/input
[=================================================================] 100.00% 370 0s 92ms
Time for merging to input_ss: 0h 0m 0s 3ms
Time for merging to input_h: 0h 0m 0s 1ms
Time for merging to input_ca: 0h 0m 0s 1ms
Time for merging to input: 0h 0m 0s 1ms
Ignore 0 out of 370.
Too short: 0, incorrect: 0, not proteins: 0.
Time for processing: 0h 0m 0s 112ms
Create directory /content/default/tmp/15576934524713146554/clu_tmp
cluster /content/default/tmp/15576934524713146554/input /content/default/tmp/15576934524713146554/clu /content/default/tmp/15576934524713146554/clu_tmp --tmscore-threshold 0.5 --tmscore-threshold-mode 0 --alignment-type 1 --remove-tmp-files 1

Set cluster sensitivity to -s 8.000000
Set cluster mode SET COVER
Set cluster iterations to 3
kmermatcher /content/default/tmp/15576934524713146554/input_ss /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pref --sub-mat 'aa:3di.out,nucl:3di.out' --alph-size aa:21,nucl:5 --min-seq-id 0 --kmer-per-seq 300 --spaced-kmer-mode 1 --kmer-per-seq-scale aa:0.000,nucl:0.200 --adjust-kmer-len 0 --mask 0 --mask-prob 0.999995 --mask-lower-case 1 --mask-n-repeat 6 --cov-mode 0 -k 0 -c 0.8 --max-seq-len 65535 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --threads 48 --compressed 0 -v 3 --cluster-weight-threshold 0.9

kmermatcher /content/default/tmp/15576934524713146554/input_ss /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pref --sub-mat 'aa:3di.out,nucl:3di.out' --alph-size aa:21,nucl:5 --min-seq-id 0 --kmer-per-seq 300 --spaced-kmer-mode 1 --kmer-per-seq-scale aa:0.000,nucl:0.200 --adjust-kmer-len 0 --mask 0 --mask-prob 0.999995 --mask-lower-case 1 --mask-n-repeat 6 --cov-mode 0 -k 0 -c 0.8 --max-seq-len 65535 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --threads 48 --compressed 0 -v 3 --cluster-weight-threshold 0.9

Database size: 370 type: Aminoacid
Reduced amino acid alphabet: (A F) (C V) (D B) (E Z) (G H) (I M T) (K W) (L J) (N R S) (P) (Q) (Y) (X)

Generate k-mers list for 1 split
[=================================================================] 100.00% 370 0s 77ms
Sort kmer 0h 0m 0s 0ms
Sort by rep. sequence 0h 0m 0s 1ms
Time for fill: 0h 0m 0s 0ms
Time for merging to pref: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 92ms
structurerescorediagonal /content/default/tmp/15576934524713146554/input /content/default/tmp/15576934524713146554/input /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pref /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pref_rescore1 --exact-tmscore 0 --tmscore-threshold 0.5 --tmscore-threshold-mode 0 --lddt-threshold 0 --alignment-type 1 --sub-mat 'aa:3di.out,nucl:3di.out' -a 0 --alignment-mode 3 --alignment-output-mode 0 --wrapped-scoring 0 -e 0.01 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0.8 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 0 --comp-bias-corr-scale 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 1 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --corr-score-weight 0 --gap-open aa:10,nucl:10 --gap-extend aa:1,nucl:1 --zdrop 40 --threads 48 --compressed 0 -v 3

[=================================================================] 100.00% 370 0s 15ms
Time for merging to pref_rescore1: 0h 0m 0s 2ms
Time for processing: 0h 0m 0s 66ms
clust /content/default/tmp/15576934524713146554/input /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pref_rescore1 /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pre_clust --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 48 --compressed 0 -v 3 --cluster-weight-threshold 0.9 --set-mode 0

Clustering mode: Set Cover
[=================================================================] 100.00% 370 0s 14ms
Sort entries
Find missing connections
Found 37 new connections.
Reconstruct initial order
[=================================================================] 100.00% 370 0s 81ms
Add missing connections
[=================================================================] 100.00% 370 0s 0ms

Time for read in: 0h 0m 0s 116ms
Total time: 0h 0m 0s 117ms

Size of the sequence database: 370
Size of the alignment database: 370
Number of clusters: 339

Writing results 0h 0m 0s 0ms
Time for merging to pre_clust: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 118ms
createsubdb /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/order_redundancy /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pref /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pref_filter1 -v 3 --subdb-mode 1

createsubdb /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/order_redundancy /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pref /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pref_filter1 --subdb-mode 1 --id-mode 0 -v 3

Time for merging to pref_filter1: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
filterdb /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pref_filter1 /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pref_filter2 --filter-file /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/order_redundancy --threads 48 --compressed 0 -v 3

Filtering using file(s)
[=================================================================] 100.00% 339 0s 73ms
Time for merging to pref_filter2: 0h 0m 0s 1ms
Time for processing: 0h 0m 0s 94ms
tmalign /content/default/tmp/15576934524713146554/input /content/default/tmp/15576934524713146554/input /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pref_filter2 /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/aln.linclust --min-seq-id 0 -c 0.8 --cov-mode 0 --max-rejected 2147483647 --max-accept 2147483647 -a 0 --add-self-matches 0 --tmscore-threshold 0.5 --tmscore-threshold-mode 0 --tmalign-hit-order 0 --tmalign-fast 1 --db-load-mode 0 --threads 48 -v 3

Query database: /content/default/tmp/15576934524713146554/input
Target database: /content/default/tmp/15576934524713146554/input
[=================================================================] 100.00% 339 1s 174ms
Time for merging to aln.linclust: 0h 0m 0s 0ms
Time for processing: 0h 0m 1s 176ms
createsubdb /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/order_redundancy /content/default/tmp/15576934524713146554/input /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pre_clustered_seqs -v 3 --subdb-mode 1

createsubdb /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/order_redundancy /content/default/tmp/15576934524713146554/input /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pre_clustered_seqs --subdb-mode 1 --id-mode 0 -v 3

Time for merging to pre_clustered_seqs: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
createsubdb /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pre_clustered_seqs.indextmp /content/default/tmp/15576934524713146554/input_ss /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pre_clustered_seqs_ss --subdb-mode 1 --id-mode 0 -v 3

Time for merging to pre_clustered_seqs_ss: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
createsubdb /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pre_clustered_seqs.indextmp /content/default/tmp/15576934524713146554/input_ca /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pre_clustered_seqs_ca --subdb-mode 1 --id-mode 0 -v 3

Time for merging to pre_clustered_seqs_ca: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
clust /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pre_clustered_seqs /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/aln.linclust /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/clust.linclust --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 48 --compressed 0 -v 3 --cluster-weight-threshold 0.9 --set-mode 0

Clustering mode: Set Cover
[=================================================================] 100.00% 339 0s 1ms
Sort entries
Find missing connections
Found 232 new connections.
Reconstruct initial order
[=================================================================] 100.00% 339 0s 7ms
Add missing connections
[=================================================================] 100.00% 339 0s 0ms

Time for read in: 0h 0m 0s 9ms
Total time: 0h 0m 0s 9ms

Size of the sequence database: 339
Size of the alignment database: 339
Number of clusters: 224

Writing results 0h 0m 0s 0ms
Time for merging to clust.linclust: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 10ms
mergeclusters /content/default/tmp/15576934524713146554/input /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/clu_redundancy /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pre_clust /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/clust.linclust --threads 48 --compressed 0 -v 3

Clustering step 1
[=================================================================] 100.00% 339 0s 98ms
Clustering step 2
[=================================================================] 100.00% 224 0s 108ms
Write merged clustering
[=================================================================] 100.00% 370 0s 198ms
Time for merging to clu_redundancy: 0h 0m 0s 1ms
Time for processing: 0h 0m 0s 203ms
createsubdb /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/clu_redundancy /content/default/tmp/15576934524713146554/input /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/input_step_redundancy -v 3 --subdb-mode 1

createsubdb /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/clu_redundancy /content/default/tmp/15576934524713146554/input /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/input_step_redundancy --subdb-mode 1 --id-mode 0 -v 3

Time for merging to input_step_redundancy: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
createsubdb /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/input_step_redundancy.indextmp /content/default/tmp/15576934524713146554/input_ss /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/input_step_redundancy_ss --subdb-mode 1 --id-mode 0 -v 3

Time for merging to input_step_redundancy_ss: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
createsubdb /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/input_step_redundancy.indextmp /content/default/tmp/15576934524713146554/input_ca /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/input_step_redundancy_ca --subdb-mode 1 --id-mode 0 -v 3

Time for merging to input_step_redundancy_ca: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
prefilter /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/input_step_redundancy_ss /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/input_step_redundancy_ss /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pref_step0 --sub-mat 'aa:3di.out,nucl:3di.out' --seed-sub-mat 'aa:3di.out,nucl:3di.out' -s 1 -k 0 --target-search-mode 0 --k-score seq:2147483647,prof:2147483647 --alph-size aa:21,nucl:5 --max-seq-len 65535 --max-seqs 100 --split 0 --split-mode 2 --split-memory-limit 0 -c 0.8 --cov-mode 0 --comp-bias-corr 0 --comp-bias-corr-scale 1 --diag-score 0 --exact-kmer-matching 0 --mask 0 --mask-prob 0.999995 --mask-lower-case 1 --mask-n-repeat 6 --min-ungapped-score 0 --add-self-matches 1 --spaced-kmer-mode 1 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --threads 48 --compressed 0 -v 3

Query database size: 224 type: Aminoacid
Estimated memory consumption: 978M
Target database size: 224 type: Aminoacid
Index table k-mer threshold: 154 at k-mer size 6
Index table: counting k-mers
[=================================================================] 100.00% 224 0s 0ms
Index table: Masked residues: 1201
Index table: fill
[=================================================================] 100.00% 224 0s 16ms
Index statistics
Entries:          2201
DB size:          488 MB
Avg k-mer size:   0.000034
Top 10 k-mers
    DKKKDD	9
    EEEEDD	7
    DDQIKM	7
    DKKKDW	7
    DKKKDA	6
    IKKWDP	6
    HYYYDP	6
    IKKKMA	5
    IMMMDD	5
    IKKWDD	5
Time for index table init: 0h 0m 0s 187ms
Process prefiltering step 1 of 1

k-mer similarity threshold: 154
Starting prefiltering scores calculation (step 1 of 1)
Query db start 1 to 224
Target db start 1 to 224
[=================================================================] 100.00% 224 0s 1ms
[==============================================================>  ] 95.96% 215 eta 0s
6.199271 k-mers per position
37 DB matches per sequence
0 overflows
4 sequences passed prefiltering per query sequence
1 median result list length
0 sequences with 0 size result lists
Time for merging to pref_step0: 0h 0m 0s 2ms
Time for processing: 0h 0m 0s 330ms
tmalign /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/input_step_redundancy /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/input_step_redundancy /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/pref_step0 /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/aln_step0 --min-seq-id 0 -c 0.8 --cov-mode 0 --max-rejected 2147483647 --max-accept 2147483647 -a 0 --add-self-matches 0 --tmscore-threshold 0.5 --tmscore-threshold-mode 0 --tmalign-hit-order 0 --tmalign-fast 1 --db-load-mode 0 --threads 48 -v 3

Query database: /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/input_step_redundancy
Target database: /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/input_step_redundancy
[=================================================================] 100.00% 224 0s 268ms
Time for merging to aln_step0: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 271ms
clust /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/input_step_redundancy /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/aln_step0 /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/clu_step0 --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 48 --compressed 0 -v 3 --cluster-weight-threshold 0.9 --set-mode 0

Clustering mode: Set Cover
[=================================================================] 100.00% 224 0s 0ms
Sort entries
Find missing connections
Found 7 new connections.
Reconstruct initial order
[=================================================================] 100.00% 224 0s 86ms
Add missing connections
[=================================================================] 100.00% 224 0s 0ms

Time for read in: 0h 0m 0s 88ms
Total time: 0h 0m 0s 89ms

Size of the sequence database: 224
Size of the alignment database: 224
Number of clusters: 208

Writing results 0h 0m 0s 0ms
Time for merging to clu_step0: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 89ms
createsubdb /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/clu_step0 /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/input_step_redundancy /content/default/tmp/15576934524713146554/clu_tmp/16668139561126317918/input_step1 -v 3 --subdb-mode 1


In [ ]:
cluster=pd.read_csv("/content/default/res_cluster.tsv", sep="\t", header=None)
cluster

                    0                 1
0    len_121_sample_7  len_121_sample_7
1    len_121_sample_7  len_126_sample_5
2    len_122_sample_2  len_122_sample_2
3    len_122_sample_6  len_122_sample_6
4    len_122_sample_6  len_105_sample_5
..                ...               ...
365  len_107_sample_4  len_124_sample_9
366  len_108_sample_2  len_108_sample_2
367  len_108_sample_3  len_108_sample_3
368  len_108_sample_9  len_108_sample_9
369  len_109_sample_0  len_109_sample_0

[370 rows x 2 columns]

In [ ]:
num_clusters = cluster[0].nunique()
print("Number of clusters:", num_clusters)

Number of clusters: 119

## Very low noise

In [ ]:
!mkdir -p /content/very_low_noise/tmp
!mkdir -p /content/very_low_noise/res

In [ ]:
!foldseek easy-cluster /content/very_low_noise_designable_samples /content/very_low_noise/res /content/very_low_noise/tmp --alignment-type 1 --tmscore-threshold 0.5 --tmscore-threshold-mode 0

/content/very_low_noise/res exists and will be overwritten
easy-cluster /content/very_low_noise_designable_samples /content/very_low_noise/res /content/very_low_noise/tmp --alignment-type 1 --tmscore-threshold 0.5 --tmscore-threshold-mode 0

MMseqs Version:                     	8dc75c74ad0eddab73cfd905963d13bf74dc012b
Substitution matrix                 	aa:3di.out,nucl:3di.out
Seed substitution matrix            	aa:3di.out,nucl:3di.out
Sensitivity                         	4
k-mer length                        	0
Target search mode                  	0
k-score                             	seq:2147483647,prof:2147483647
Max sequence length                 	65535
Max results per query               	300
Split database                      	0
Split mode                          	2
Split memory limit                  	0
Coverage threshold                  	0
Coverage mode                       	0
Compositional bias                  	1
Compositional bias scale            	1
Diagonal scoring                    	true
Exact k-mer matching                	0
Mask residues                       	0
Mask residues probability           	0.999995
Mask lower case residues            	1
Mask lower letter repeating N times 	6
Minimum diagonal score              	30
Selected taxa
Spaced k-mers                       	1
Preload mode                        	0
Spaced k-mer pattern
Local temporary path
Threads                             	48
Compressed                          	0
Verbosity                           	3
TMscore threshold                   	0.5
TMscore threshold mode              	0
LDDT threshold                      	0
Sort by structure bit score         	1
Alignment type                      	1
Exact TMscore                       	0
Add backtrace                       	false
Alignment mode                      	0
Alignment mode                      	0
E-value threshold                   	10
Seq. id. threshold                  	0
Min alignment length                	0
Seq. id. mode                       	0
Alternative alignments              	0
Max reject                          	2147483647
Max accept                          	2147483647
Gap open cost                       	aa:10,nucl:10
Gap extension cost                  	aa:1,nucl:1
TMalign hit order                   	0
TMalign fast                        	1
Cluster mode                        	0
Max connected component depth       	1000
Similarity type                     	2
Weight file name
Cluster Weight threshold            	0.9
Set mode                            	false
Single step clustering              	false
Cascaded clustering steps           	3
Cluster reassign                    	false
Remove temporary files              	true
Force restart with latest tmp       	false
MPI runner
k-mers per sequence                 	21
Scale k-mers per sequence           	aa:0.000,nucl:0.200
Adjust k-mer length                 	false
Shift hash                          	67
Include only extendable             	false
Skip repeating k-mers               	false
Rescore mode                        	0
Remove hits by seq. id. and coverage	false
Sort results                        	0
Use GPU                             	0
Path to ProstT5
Chain name mode                     	0
Model name mode                     	0
Createdb extraction mode            	0
Interface distance threshold        	10
Write mapping file                  	0
Write Foldcomp                      	0
Mask b-factor threshold             	0
Coord store mode                    	2
Write lookup file                   	1
Input format                        	0
Input compression format            	0
File Inclusion Regex                	.*
File Exclusion Regex                	^$

createdb /content/very_low_noise_designable_samples /content/very_low_noise/tmp/7465819597389282959/input --gpu 0 --chain-name-mode 0 --model-name-mode 0 --db-extraction-mode 0 --distance-threshold 10 --write-mapping 0 --write-foldcomp 0 --mask-bfactor-threshold 0 --coord-store-mode 2 --write-lookup 1 --input-format 0 --input-compression-format 0 --file-include '.*' --file-exclude '^$' --threads 48 -v 3

Output file: /content/very_low_noise/tmp/7465819597389282959/input
[=================================================================] 100.00% 388 0s 92ms
Time for merging to input_ss: 0h 0m 0s 2ms
Time for merging to input_h: 0h 0m 0s 1ms
Time for merging to input_ca: 0h 0m 0s 1ms
Time for merging to input: 0h 0m 0s 1ms
Ignore 0 out of 388.
Too short: 0, incorrect: 0, not proteins: 0.
Time for processing: 0h 0m 0s 108ms
Create directory /content/very_low_noise/tmp/7465819597389282959/clu_tmp
cluster /content/very_low_noise/tmp/7465819597389282959/input /content/very_low_noise/tmp/7465819597389282959/clu /content/very_low_noise/tmp/7465819597389282959/clu_tmp --tmscore-threshold 0.5 --tmscore-threshold-mode 0 --alignment-type 1 --remove-tmp-files 1

Set cluster sensitivity to -s 8.000000
Set cluster mode SET COVER
Set cluster iterations to 3
kmermatcher /content/very_low_noise/tmp/7465819597389282959/input_ss /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pref --sub-mat 'aa:3di.out,nucl:3di.out' --alph-size aa:21,nucl:5 --min-seq-id 0 --kmer-per-seq 300 --spaced-kmer-mode 1 --kmer-per-seq-scale aa:0.000,nucl:0.200 --adjust-kmer-len 0 --mask 0 --mask-prob 0.999995 --mask-lower-case 1 --mask-n-repeat 6 --cov-mode 0 -k 0 -c 0.8 --max-seq-len 65535 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --threads 48 --compressed 0 -v 3 --cluster-weight-threshold 0.9

kmermatcher /content/very_low_noise/tmp/7465819597389282959/input_ss /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pref --sub-mat 'aa:3di.out,nucl:3di.out' --alph-size aa:21,nucl:5 --min-seq-id 0 --kmer-per-seq 300 --spaced-kmer-mode 1 --kmer-per-seq-scale aa:0.000,nucl:0.200 --adjust-kmer-len 0 --mask 0 --mask-prob 0.999995 --mask-lower-case 1 --mask-n-repeat 6 --cov-mode 0 -k 0 -c 0.8 --max-seq-len 65535 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --threads 48 --compressed 0 -v 3 --cluster-weight-threshold 0.9

Database size: 388 type: Aminoacid
Reduced amino acid alphabet: (A F) (C V) (D B) (E Z) (G H) (I M T) (K W) (L J) (N R S) (P) (Q) (Y) (X)

Generate k-mers list for 1 split
[=================================================================] 100.00% 388 0s 81ms
Sort kmer 0h 0m 0s 0ms
Sort by rep. sequence 0h 0m 0s 1ms
Time for fill: 0h 0m 0s 0ms
Time for merging to pref: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 92ms
structurerescorediagonal /content/very_low_noise/tmp/7465819597389282959/input /content/very_low_noise/tmp/7465819597389282959/input /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pref /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pref_rescore1 --exact-tmscore 0 --tmscore-threshold 0.5 --tmscore-threshold-mode 0 --lddt-threshold 0 --alignment-type 1 --sub-mat 'aa:3di.out,nucl:3di.out' -a 0 --alignment-mode 3 --alignment-output-mode 0 --wrapped-scoring 0 -e 0.01 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0.8 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 0 --comp-bias-corr-scale 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 1 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --corr-score-weight 0 --gap-open aa:10,nucl:10 --gap-extend aa:1,nucl:1 --zdrop 40 --threads 48 --compressed 0 -v 3

[=================================================================] 100.00% 388 0s 15ms
Time for merging to pref_rescore1: 0h 0m 0s 2ms
Time for processing: 0h 0m 0s 73ms
clust /content/very_low_noise/tmp/7465819597389282959/input /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pref_rescore1 /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pre_clust --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 48 --compressed 0 -v 3 --cluster-weight-threshold 0.9 --set-mode 0

Clustering mode: Set Cover
[=================================================================] 100.00% 388 0s 11ms
Sort entries
Find missing connections
Found 272 new connections.
Reconstruct initial order
[=================================================================] 100.00% 388 0s 3ms
Add missing connections
[=================================================================] 100.00% 388 0s 89ms

Time for read in: 0h 0m 0s 111ms
Total time: 0h 0m 0s 112ms

Size of the sequence database: 388
Size of the alignment database: 388
Number of clusters: 255

Writing results 0h 0m 0s 0ms
Time for merging to pre_clust: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 113ms
createsubdb /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/order_redundancy /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pref /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pref_filter1 -v 3 --subdb-mode 1

createsubdb /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/order_redundancy /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pref /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pref_filter1 --subdb-mode 1 --id-mode 0 -v 3

Time for merging to pref_filter1: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
filterdb /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pref_filter1 /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pref_filter2 --filter-file /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/order_redundancy --threads 48 --compressed 0 -v 3

Filtering using file(s)
[=================================================================] 100.00% 255 0s 1ms
Time for merging to pref_filter2: 0h 0m 0s 1ms
Time for processing: 0h 0m 0s 28ms
tmalign /content/very_low_noise/tmp/7465819597389282959/input /content/very_low_noise/tmp/7465819597389282959/input /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pref_filter2 /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/aln.linclust --min-seq-id 0 -c 0.8 --cov-mode 0 --max-rejected 2147483647 --max-accept 2147483647 -a 0 --add-self-matches 0 --tmscore-threshold 0.5 --tmscore-threshold-mode 0 --tmalign-hit-order 0 --tmalign-fast 1 --db-load-mode 0 --threads 48 -v 3

Query database: /content/very_low_noise/tmp/7465819597389282959/input
Target database: /content/very_low_noise/tmp/7465819597389282959/input
[=================================================================] 100.00% 255 0s 857ms
Time for merging to aln.linclust: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 922ms
createsubdb /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/order_redundancy /content/very_low_noise/tmp/7465819597389282959/input /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pre_clustered_seqs -v 3 --subdb-mode 1

createsubdb /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/order_redundancy /content/very_low_noise/tmp/7465819597389282959/input /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pre_clustered_seqs --subdb-mode 1 --id-mode 0 -v 3

Time for merging to pre_clustered_seqs: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
createsubdb /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pre_clustered_seqs.indextmp /content/very_low_noise/tmp/7465819597389282959/input_ss /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pre_clustered_seqs_ss --subdb-mode 1 --id-mode 0 -v 3

Time for merging to pre_clustered_seqs_ss: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
createsubdb /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pre_clustered_seqs.indextmp /content/very_low_noise/tmp/7465819597389282959/input_ca /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pre_clustered_seqs_ca --subdb-mode 1 --id-mode 0 -v 3

Time for merging to pre_clustered_seqs_ca: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
clust /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pre_clustered_seqs /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/aln.linclust /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/clust.linclust --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 48 --compressed 0 -v 3 --cluster-weight-threshold 0.9 --set-mode 0

Clustering mode: Set Cover
[=================================================================] 100.00% 255 0s 0ms
Sort entries
Find missing connections
Found 575 new connections.
Reconstruct initial order
[=================================================================] 100.00% 255 0s 33ms
Add missing connections
[=================================================================] 100.00% 255 0s 0ms

Time for read in: 0h 0m 0s 34ms
Total time: 0h 0m 0s 34ms

Size of the sequence database: 255
Size of the alignment database: 255
Number of clusters: 106

Writing results 0h 0m 0s 0ms
Time for merging to clust.linclust: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 35ms
mergeclusters /content/very_low_noise/tmp/7465819597389282959/input /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/clu_redundancy /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pre_clust /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/clust.linclust --threads 48 --compressed 0 -v 3

Clustering step 1
[=================================================================] 100.00% 255 0s 0ms
Clustering step 2
[=================================================================] 100.00% 106 0s 98ms
Write merged clustering
[=================================================================] 100.00% 388 0s 110ms
Time for merging to clu_redundancy: 0h 0m 0s 1ms
Time for processing: 0h 0m 0s 118ms
createsubdb /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/clu_redundancy /content/very_low_noise/tmp/7465819597389282959/input /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/input_step_redundancy -v 3 --subdb-mode 1

createsubdb /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/clu_redundancy /content/very_low_noise/tmp/7465819597389282959/input /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/input_step_redundancy --subdb-mode 1 --id-mode 0 -v 3

Time for merging to input_step_redundancy: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
createsubdb /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/input_step_redundancy.indextmp /content/very_low_noise/tmp/7465819597389282959/input_ss /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/input_step_redundancy_ss --subdb-mode 1 --id-mode 0 -v 3

Time for merging to input_step_redundancy_ss: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
createsubdb /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/input_step_redundancy.indextmp /content/very_low_noise/tmp/7465819597389282959/input_ca /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/input_step_redundancy_ca --subdb-mode 1 --id-mode 0 -v 3

Time for merging to input_step_redundancy_ca: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
prefilter /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/input_step_redundancy_ss /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/input_step_redundancy_ss /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pref_step0 --sub-mat 'aa:3di.out,nucl:3di.out' --seed-sub-mat 'aa:3di.out,nucl:3di.out' -s 1 -k 0 --target-search-mode 0 --k-score seq:2147483647,prof:2147483647 --alph-size aa:21,nucl:5 --max-seq-len 65535 --max-seqs 100 --split 0 --split-mode 2 --split-memory-limit 0 -c 0.8 --cov-mode 0 --comp-bias-corr 0 --comp-bias-corr-scale 1 --diag-score 0 --exact-kmer-matching 0 --mask 0 --mask-prob 0.999995 --mask-lower-case 1 --mask-n-repeat 6 --min-ungapped-score 0 --add-self-matches 1 --spaced-kmer-mode 1 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --threads 48 --compressed 0 -v 3

Query database size: 106 type: Aminoacid
Estimated memory consumption: 978M
Target database size: 106 type: Aminoacid
Index table k-mer threshold: 154 at k-mer size 6
Index table: counting k-mers
[=================================================================] 100.00% 106 0s 0ms
Index table: Masked residues: 174
Index table: fill
[=================================================================] 100.00% 106 0s 0ms
Index statistics
Entries:          231
DB size:          488 MB
Avg k-mer size:   0.000004
Top 10 k-mers
    EEEEPV	2
    KEEEEA	1
    DAEFEA	1
    QWKKMA	1
    DKKKQA	1
    AGEAYA	1
    PAEEYA	1
    TAEEYA	1
    AEEEPC	1
    DMMGPC	1
Time for index table init: 0h 0m 0s 169ms
Process prefiltering step 1 of 1

k-mer similarity threshold: 154
Starting prefiltering scores calculation (step 1 of 1)
Query db start 1 to 106
Target db start 1 to 106
[=================================================================] 100.00% 106 0s 1ms
[=======================================================>         ] 85.71% 91 eta 0s
1.283411 k-mers per position
2 DB matches per sequence
0 overflows
1 sequences passed prefiltering per query sequence
1 median result list length
0 sequences with 0 size result lists
Time for merging to pref_step0: 0h 0m 0s 1ms
Time for processing: 0h 0m 0s 267ms
tmalign /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/input_step_redundancy /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/input_step_redundancy /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/pref_step0 /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/aln_step0 --min-seq-id 0 -c 0.8 --cov-mode 0 --max-rejected 2147483647 --max-accept 2147483647 -a 0 --add-self-matches 0 --tmscore-threshold 0.5 --tmscore-threshold-mode 0 --tmalign-hit-order 0 --tmalign-fast 1 --db-load-mode 0 --threads 48 -v 3

Query database: /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/input_step_redundancy
Target database: /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/input_step_redundancy
[=================================================================] 100.00% 106 0s 15ms
Time for merging to aln_step0: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 16ms
clust /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/input_step_redundancy /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/aln_step0 /content/very_low_noise/tmp/7465819597389282959/clu_tmp/16745068141271025973/clu_step0 --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 48 --compressed 0 -v 3 --cluster-weight-threshold 0.9 --set-mode 0

Clustering mode: Set Cover
[=================================================================] 100.00% 106 0s 0ms
Sort entries
Find missing connections
Found 1 new connections.
Reconstruct initial order
[=================================================================] 100.00% 106 0s 0ms
Add missing connections
[=================================================================] 100.00% 106 0s 86ms

Time for read in: 0h 0m 0s 86ms
Total time: 0h 0m 0s 93ms

Size of the sequence database: 106
Size of the alignment database: 106
Number of clusters: 105

Writing results 0h 0m 0s 0ms

In [ ]:
cluster=pd.read_csv("/content/very_low_noise/res_cluster.tsv", sep="\t", header=None)

In [ ]:
num_clusters = cluster[0].nunique()
print("Number of clusters:", num_clusters)

Number of clusters: 29

## fast

In [ ]:
!mkdir -p /content/fast/tmp
!mkdir -p /content/fast/res

In [ ]:
!foldseek easy-cluster /content/fast_designable_samples /content/fast/res /content/fast/tmp --alignment-type 1 --tmscore-threshold 0.5 --tmscore-threshold-mode 0

/content/fast/res exists and will be overwritten
easy-cluster /content/fast_designable_samples /content/fast/res /content/fast/tmp --alignment-type 1 --tmscore-threshold 0.5 --tmscore-threshold-mode 0

MMseqs Version:                     	8dc75c74ad0eddab73cfd905963d13bf74dc012b
Substitution matrix                 	aa:3di.out,nucl:3di.out
Seed substitution matrix            	aa:3di.out,nucl:3di.out
Sensitivity                         	4
k-mer length                        	0
Target search mode                  	0
k-score                             	seq:2147483647,prof:2147483647
Max sequence length                 	65535
Max results per query               	300
Split database                      	0
Split mode                          	2
Split memory limit                  	0
Coverage threshold                  	0
Coverage mode                       	0
Compositional bias                  	1
Compositional bias scale            	1
Diagonal scoring                    	true
Exact k-mer matching                	0
Mask residues                       	0
Mask residues probability           	0.999995
Mask lower case residues            	1
Mask lower letter repeating N times 	6
Minimum diagonal score              	30
Selected taxa
Spaced k-mers                       	1
Preload mode                        	0
Spaced k-mer pattern
Local temporary path
Threads                             	48
Compressed                          	0
Verbosity                           	3
TMscore threshold                   	0.5
TMscore threshold mode              	0
LDDT threshold                      	0
Sort by structure bit score         	1
Alignment type                      	1
Exact TMscore                       	0
Add backtrace                       	false
Alignment mode                      	0
Alignment mode                      	0
E-value threshold                   	10
Seq. id. threshold                  	0
Min alignment length                	0
Seq. id. mode                       	0
Alternative alignments              	0
Max reject                          	2147483647
Max accept                          	2147483647
Gap open cost                       	aa:10,nucl:10
Gap extension cost                  	aa:1,nucl:1
TMalign hit order                   	0
TMalign fast                        	1
Cluster mode                        	0
Max connected component depth       	1000
Similarity type                     	2
Weight file name
Cluster Weight threshold            	0.9
Set mode                            	false
Single step clustering              	false
Cascaded clustering steps           	3
Cluster reassign                    	false
Remove temporary files              	true
Force restart with latest tmp       	false
MPI runner
k-mers per sequence                 	21
Scale k-mers per sequence           	aa:0.000,nucl:0.200
Adjust k-mer length                 	false
Shift hash                          	67
Include only extendable             	false
Skip repeating k-mers               	false
Rescore mode                        	0
Remove hits by seq. id. and coverage	false
Sort results                        	0
Use GPU                             	0
Path to ProstT5
Chain name mode                     	0
Model name mode                     	0
Createdb extraction mode            	0
Interface distance threshold        	10
Write mapping file                  	0
Write Foldcomp                      	0
Mask b-factor threshold             	0
Coord store mode                    	2
Write lookup file                   	1
Input format                        	0
Input compression format            	0
File Inclusion Regex                	.*
File Exclusion Regex                	^$

createdb /content/fast_designable_samples /content/fast/tmp/5175056060253922065/input --gpu 0 --chain-name-mode 0 --model-name-mode 0 --db-extraction-mode 0 --distance-threshold 10 --write-mapping 0 --write-foldcomp 0 --mask-bfactor-threshold 0 --coord-store-mode 2 --write-lookup 1 --input-format 0 --input-compression-format 0 --file-include '.*' --file-exclude '^$' --threads 48 -v 3

Output file: /content/fast/tmp/5175056060253922065/input
[=================================================================] 100.00% 341 0s 7ms
Time for merging to input_ss: 0h 0m 0s 2ms
Time for merging to input_h: 0h 0m 0s 1ms
Time for merging to input_ca: 0h 0m 0s 1ms
Time for merging to input: 0h 0m 0s 1ms
Ignore 0 out of 341.
Too short: 0, incorrect: 0, not proteins: 0.
Time for processing: 0h 0m 0s 27ms
Create directory /content/fast/tmp/5175056060253922065/clu_tmp
cluster /content/fast/tmp/5175056060253922065/input /content/fast/tmp/5175056060253922065/clu /content/fast/tmp/5175056060253922065/clu_tmp --tmscore-threshold 0.5 --tmscore-threshold-mode 0 --alignment-type 1 --remove-tmp-files 1

Set cluster sensitivity to -s 8.000000
Set cluster mode SET COVER
Set cluster iterations to 3
kmermatcher /content/fast/tmp/5175056060253922065/input_ss /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pref --sub-mat 'aa:3di.out,nucl:3di.out' --alph-size aa:21,nucl:5 --min-seq-id 0 --kmer-per-seq 300 --spaced-kmer-mode 1 --kmer-per-seq-scale aa:0.000,nucl:0.200 --adjust-kmer-len 0 --mask 0 --mask-prob 0.999995 --mask-lower-case 1 --mask-n-repeat 6 --cov-mode 0 -k 0 -c 0.8 --max-seq-len 65535 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --threads 48 --compressed 0 -v 3 --cluster-weight-threshold 0.9

kmermatcher /content/fast/tmp/5175056060253922065/input_ss /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pref --sub-mat 'aa:3di.out,nucl:3di.out' --alph-size aa:21,nucl:5 --min-seq-id 0 --kmer-per-seq 300 --spaced-kmer-mode 1 --kmer-per-seq-scale aa:0.000,nucl:0.200 --adjust-kmer-len 0 --mask 0 --mask-prob 0.999995 --mask-lower-case 1 --mask-n-repeat 6 --cov-mode 0 -k 0 -c 0.8 --max-seq-len 65535 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --threads 48 --compressed 0 -v 3 --cluster-weight-threshold 0.9

Database size: 341 type: Aminoacid
Reduced amino acid alphabet: (A F) (C V) (D B) (E Z) (G H) (I M T) (K W) (L J) (N R S) (P) (Q) (Y) (X)

Generate k-mers list for 1 split
[=================================================================] 100.00% 341 0s 4ms
Sort kmer 0h 0m 0s 0ms
Sort by rep. sequence 0h 0m 0s 0ms
Time for fill: 0h 0m 0s 0ms
Time for merging to pref: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 98ms
structurerescorediagonal /content/fast/tmp/5175056060253922065/input /content/fast/tmp/5175056060253922065/input /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pref /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pref_rescore1 --exact-tmscore 0 --tmscore-threshold 0.5 --tmscore-threshold-mode 0 --lddt-threshold 0 --alignment-type 1 --sub-mat 'aa:3di.out,nucl:3di.out' -a 0 --alignment-mode 3 --alignment-output-mode 0 --wrapped-scoring 0 -e 0.01 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0.8 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 0 --comp-bias-corr-scale 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 1 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --corr-score-weight 0 --gap-open aa:10,nucl:10 --gap-extend aa:1,nucl:1 --zdrop 40 --threads 48 --compressed 0 -v 3

[=================================================================] 100.00% 341 0s 14ms
Time for merging to pref_rescore1: 0h 0m 0s 2ms
Time for processing: 0h 0m 0s 67ms
clust /content/fast/tmp/5175056060253922065/input /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pref_rescore1 /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pre_clust --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 48 --compressed 0 -v 3 --cluster-weight-threshold 0.9 --set-mode 0

Clustering mode: Set Cover
[=================================================================] 100.00% 341 0s 12ms
Sort entries
Find missing connections
Found 5 new connections.
Reconstruct initial order
[=================================================================] 100.00% 341 0s 3ms
Add missing connections
[=================================================================] 100.00% 341 0s 81ms

Time for read in: 0h 0m 0s 117ms
Total time: 0h 0m 0s 125ms

Size of the sequence database: 341
Size of the alignment database: 341
Number of clusters: 336

Writing results 0h 0m 0s 0ms
Time for merging to pre_clust: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 126ms
createsubdb /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/order_redundancy /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pref /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pref_filter1 -v 3 --subdb-mode 1

createsubdb /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/order_redundancy /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pref /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pref_filter1 --subdb-mode 1 --id-mode 0 -v 3

Time for merging to pref_filter1: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
filterdb /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pref_filter1 /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pref_filter2 --filter-file /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/order_redundancy --threads 48 --compressed 0 -v 3

Filtering using file(s)
[=================================================================] 100.00% 336 0s 1ms
Time for merging to pref_filter2: 0h 0m 0s 1ms
Time for processing: 0h 0m 0s 24ms
tmalign /content/fast/tmp/5175056060253922065/input /content/fast/tmp/5175056060253922065/input /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pref_filter2 /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/aln.linclust --min-seq-id 0 -c 0.8 --cov-mode 0 --max-rejected 2147483647 --max-accept 2147483647 -a 0 --add-self-matches 0 --tmscore-threshold 0.5 --tmscore-threshold-mode 0 --tmalign-hit-order 0 --tmalign-fast 1 --db-load-mode 0 --threads 48 -v 3

Query database: /content/fast/tmp/5175056060253922065/input
Target database: /content/fast/tmp/5175056060253922065/input
[=================================================================] 100.00% 336 1s 83ms
Time for merging to aln.linclust: 0h 0m 0s 0ms
Time for processing: 0h 0m 1s 84ms
createsubdb /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/order_redundancy /content/fast/tmp/5175056060253922065/input /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pre_clustered_seqs -v 3 --subdb-mode 1

createsubdb /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/order_redundancy /content/fast/tmp/5175056060253922065/input /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pre_clustered_seqs --subdb-mode 1 --id-mode 0 -v 3

Time for merging to pre_clustered_seqs: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
createsubdb /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pre_clustered_seqs.indextmp /content/fast/tmp/5175056060253922065/input_ss /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pre_clustered_seqs_ss --subdb-mode 1 --id-mode 0 -v 3

Time for merging to pre_clustered_seqs_ss: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
createsubdb /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pre_clustered_seqs.indextmp /content/fast/tmp/5175056060253922065/input_ca /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pre_clustered_seqs_ca --subdb-mode 1 --id-mode 0 -v 3

Time for merging to pre_clustered_seqs_ca: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
clust /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pre_clustered_seqs /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/aln.linclust /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/clust.linclust --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 48 --compressed 0 -v 3 --cluster-weight-threshold 0.9 --set-mode 0

Clustering mode: Set Cover
[=================================================================] 100.00% 336 0s 78ms
Sort entries
Find missing connections
Found 132 new connections.
Reconstruct initial order
[=================================================================] 100.00% 336 0s 5ms
Add missing connections
[=================================================================] 100.00% 336 0s 0ms

Time for read in: 0h 0m 0s 84ms
Total time: 0h 0m 0s 84ms

Size of the sequence database: 336
Size of the alignment database: 336
Number of clusters: 253

Writing results 0h 0m 0s 0ms
Time for merging to clust.linclust: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 85ms
mergeclusters /content/fast/tmp/5175056060253922065/input /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/clu_redundancy /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pre_clust /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/clust.linclust --threads 48 --compressed 0 -v 3

Clustering step 1
[=================================================================] 100.00% 336 0s 98ms
Clustering step 2
[=================================================================] 100.00% 253 0s 101ms
Write merged clustering
[=================================================================] 100.00% 341 0s 198ms
Time for merging to clu_redundancy: 0h 0m 0s 1ms
Time for processing: 0h 0m 0s 203ms
createsubdb /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/clu_redundancy /content/fast/tmp/5175056060253922065/input /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/input_step_redundancy -v 3 --subdb-mode 1

createsubdb /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/clu_redundancy /content/fast/tmp/5175056060253922065/input /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/input_step_redundancy --subdb-mode 1 --id-mode 0 -v 3

Time for merging to input_step_redundancy: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
createsubdb /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/input_step_redundancy.indextmp /content/fast/tmp/5175056060253922065/input_ss /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/input_step_redundancy_ss --subdb-mode 1 --id-mode 0 -v 3

Time for merging to input_step_redundancy_ss: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
createsubdb /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/input_step_redundancy.indextmp /content/fast/tmp/5175056060253922065/input_ca /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/input_step_redundancy_ca --subdb-mode 1 --id-mode 0 -v 3

Time for merging to input_step_redundancy_ca: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
prefilter /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/input_step_redundancy_ss /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/input_step_redundancy_ss /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pref_step0 --sub-mat 'aa:3di.out,nucl:3di.out' --seed-sub-mat 'aa:3di.out,nucl:3di.out' -s 1 -k 0 --target-search-mode 0 --k-score seq:2147483647,prof:2147483647 --alph-size aa:21,nucl:5 --max-seq-len 65535 --max-seqs 100 --split 0 --split-mode 2 --split-memory-limit 0 -c 0.8 --cov-mode 0 --comp-bias-corr 0 --comp-bias-corr-scale 1 --diag-score 0 --exact-kmer-matching 0 --mask 0 --mask-prob 0.999995 --mask-lower-case 1 --mask-n-repeat 6 --min-ungapped-score 0 --add-self-matches 1 --spaced-kmer-mode 1 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --threads 48 --compressed 0 -v 3

Query database size: 253 type: Aminoacid
Estimated memory consumption: 978M
Target database size: 253 type: Aminoacid
Index table k-mer threshold: 154 at k-mer size 6
Index table: counting k-mers
[=================================================================] 100.00% 253 0s 0ms
Index table: Masked residues: 1240
Index table: fill
[=================================================================] 100.00% 253 0s 29ms
Index statistics
Entries:          2636
DB size:          488 MB
Avg k-mer size:   0.000041
Top 10 k-mers
    DKKKDD	13
    IKKWDP	10
    DMMMDD	7
    IKKWDD	6
    DKKKDP	5
    YYYYDP	5
    MIIIDD	4
    HYYYDD	4
    IMMMGD	4
    HYYYDH	4
Time for index table init: 0h 0m 0s 197ms
Process prefiltering step 1 of 1

k-mer similarity threshold: 154
Starting prefiltering scores calculation (step 1 of 1)
Query db start 1 to 253
Target db start 1 to 253
[=================================================================] 100.00% 253 0s 30ms
[===========================================================>     ] 92.06% 233 eta 0s
5.042133 k-mers per position
34 DB matches per sequence
0 overflows
4 sequences passed prefiltering per query sequence
1 median result list length
0 sequences with 0 size result lists
Time for merging to pref_step0: 0h 0m 0s 3ms
Time for processing: 0h 0m 0s 329ms
tmalign /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/input_step_redundancy /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/input_step_redundancy /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/pref_step0 /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/aln_step0 --min-seq-id 0 -c 0.8 --cov-mode 0 --max-rejected 2147483647 --max-accept 2147483647 -a 0 --add-self-matches 0 --tmscore-threshold 0.5 --tmscore-threshold-mode 0 --tmalign-hit-order 0 --tmalign-fast 1 --db-load-mode 0 --threads 48 -v 3

Query database: /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/input_step_redundancy
Target database: /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/input_step_redundancy
[=================================================================] 100.00% 253 0s 384ms
Time for merging to aln_step0: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 390ms
clust /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/input_step_redundancy /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/aln_step0 /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/clu_step0 --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 48 --compressed 0 -v 3 --cluster-weight-threshold 0.9 --set-mode 0

Clustering mode: Set Cover
[=================================================================] 100.00% 253 0s 0ms
Sort entries
Find missing connections
Found 4 new connections.
Reconstruct initial order
[=================================================================] 100.00% 253 0s 66ms
Add missing connections
[=================================================================] 100.00% 253 0s 0ms

Time for read in: 0h 0m 0s 67ms
Total time: 0h 0m 0s 68ms

Size of the sequence database: 253
Size of the alignment database: 253
Number of clusters: 239

Writing results 0h 0m 0s 0ms
Time for merging to clu_step0: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 68ms
createsubdb /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/clu_step0 /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/input_step_redundancy /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/input_step1 -v 3 --subdb-mode 1

createsubdb /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/clu_step0 /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/input_step_redundancy /content/fast/tmp/5175056060253922065/clu_tmp/10571100085720549089/input_step1 --subdb-mode 1 --id-mode 0 -v 3

Time for merging to input_step1: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms

In [ ]:
cluster=pd.read_csv("/content/fast/res_cluster.tsv", sep="\t", header=None)

In [ ]:
num_clusters = cluster[0].nunique()
print("Number of clusters:", num_clusters)

Number of clusters: 149

# Novelty - designable samples

## Default

In [ ]:
from google.colab import files

In [ ]:
designable = pd.read_csv("/content/default_designable.csv")
pdbtm = pd.read_csv("/content/novelty_default.csv")

In [ ]:
designable.shape

(370, 5)

In [ ]:
pdbtm.shape

(390, 3)

In [ ]:
designable_pdbtm = pdbtm.merge(
    designable[["length", "sample"]],
    on=["length", "sample"],
    how="inner"
)

In [ ]:
designable_pdbtm.shape

(370, 3)

In [ ]:
designable_pdbtm.head()

   pdbTM    sample   length
0  0.643  sample_0  len_090
1  0.731  sample_1  len_090
2  0.559  sample_3  len_090
3  0.652  sample_4  len_090
4  0.799  sample_5  len_090

In [ ]:
designable_pdbtm.to_csv("/content/novelty_default_designable.csv", index=False)
files.download("/content/novelty_default_designable.csv")

In [ ]:
print(designable_pdbtm["pdbTM"].mean())

0.7381108108108108

##Very low noise

In [ ]:
designable = pd.read_csv("/content/very_low_noise_designable.csv")
pdbtm = pd.read_csv("/content/novelty_very_low_noise.csv")
designable_pdbtm = pdbtm.merge(
    designable[["length", "sample"]],
    on=["length", "sample"],
    how="inner"
)
print(designable_pdbtm.shape)
designable_pdbtm.to_csv("/content/novelty_very_low_noise_designable.csv", index=False)
files.download("/content/novelty_very_low_noise_designable.csv")
print(designable_pdbtm["pdbTM"].mean())

(388, 3)

0.8056726804123712

##Fast

In [ ]:
designable = pd.read_csv("/content/fast_designable.csv")
pdbtm = pd.read_csv("/content/novelty_fast.csv")
designable_pdbtm = pdbtm.merge(
    designable[["length", "sample"]],
    on=["length", "sample"],
    how="inner"
)
print(designable_pdbtm.shape)
designable_pdbtm.to_csv("/content/novelty_fast_designable.csv", index=False)
files.download("/content/novelty_fast_designable.csv")
print(designable_pdbtm["pdbTM"].mean())

(341, 3)

0.7213401759530791

# Substructure - designable samples

## default

In [ ]:
designable = pd.read_csv("/content/default_designable.csv")
substructure = pd.read_csv("/content/substructure_default.csv")

In [ ]:
designable_substructure = substructure.merge(
    designable[["length", "sample"]],
    on=["length", "sample"],
    how="inner"
)

In [ ]:
designable_substructure.shape

(370, 7)

In [ ]:
designable_substructure.head()

,non_coil_percent,coil_percent,helix_percent,strand_percent,radius_of_gyration,length,sample
0,0.766667,0.233333,0.577778,0.188889,1.292837,len_090,sample_0
1,0.866667,0.133333,0.866667,0.000000,1.356013,len_090,sample_1
2,0.800000,0.200000,0.777778,0.022222,1.293698,len_090,sample_3
3,0.855556,0.144444,0.633333,0.222222,1.537325,len_090,sample_4
4,0.877778,0.122222,0.877778,0.000000,1.262205,len_090,sample_5

In [ ]:
designable_substructure.to_csv("/content/substructure_default_designable.csv", index=False)
files.download("/content/substructure_default_designable.csv")

In [ ]:
print("helix:", designable_substructure["helix_percent"].mean())
print("sheet:", designable_substructure["strand_percent"].mean())
print("coil:", designable_substructure["coil_percent"].mean())

helix: 0.7550108344033336
sheet: 0.091690903325868
coil: 0.15329826227079843

## very low noise

In [ ]:
designable = pd.read_csv("/content/very_low_noise_designable.csv")
substructure = pd.read_csv("/content/substructure_very_low_noise.csv")
designable_substructure = substructure.merge(
    designable[["length", "sample"]],
    on=["length", "sample"],
    how="inner"
)
print(designable_substructure.shape)

(388, 7)

In [ ]:
designable_substructure.to_csv("/content/substructure_very_low_noise_designable.csv", index=False)
files.download("/content/substructure_very_low_noise_designable.csv")

In [ ]:
print("helix:", designable_substructure["helix_percent"].mean())
print("sheet:", designable_substructure["strand_percent"].mean())
print("coil:", designable_substructure["coil_percent"].mean())

helix: 0.8767587964631136
sheet: 0.01137790466097863
coil: 0.11186329887590771

## fast

In [ ]:
designable = pd.read_csv("/content/fast_designable.csv")
substructure = pd.read_csv("/content/substructure_fast.csv")
designable_substructure = substructure.merge(
    designable[["length", "sample"]],
    on=["length", "sample"],
    how="inner"
)
print(designable_substructure.shape)

(341, 7)

In [ ]:
designable_substructure.to_csv("/content/substructure_fast_designable.csv", index=False)
files.download("/content/substructure_fast_designable.csv")

In [ ]:
print("helix:", designable_substructure["helix_percent"].mean())
print("sheet:", designable_substructure["strand_percent"].mean())
print("coil:", designable_substructure["coil_percent"].mean())

helix: 0.6988392538316883
sheet: 0.1251829249064771
coil: 0.17597782126183453